### PR TITLE
fix: fix user prompt function

### LINKED ISSUE #6612: Crash: inquirer.prompt is not a function
### Error message

TypeError: inquirer.prompt is not a function
    at userPrompt (file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:193198:21)
    at async DeployCommand.isAllowedToRun (file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:433698:28)
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:433518:21
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:433311:20
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:915518:26
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:915686:33
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:433311:20
    at async GardenCli.run (file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:915684:32)
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:915843:29
    at async file:///Users/anna/Library/Application%20Support/io.garden.garden/1730379796-JKx2u0O.r/rollup/garden.mjs:433311:20

### What did you do?

`garden deploy --env prod`

Where `prod` is an environment marked as `production` and therefore prompts for confirmation. The prompt fails with above error.

### Your environment

* **OS:** macOS 
* **How I'm running Kubernetes:** EKS
* **Garden version:** 0.13.43

### Frequency

It is reproducable.

### Workaround

Remove the `production` flag from the environment. However this removes the added layer of security by asking for confirmation.

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:

That has been broken since the major version update of inquirer library on 0.13.43.

**Which issue(s) this PR fixes**:

Fixes #6612

**Special notes for your reviewer**:

### CODE REVIEW

**Review by twelvemo — APPROVED** [review]
Amazing! Thanks for the quick turnaround!

File: core/src/util/util.ts [hunk 1]
```diff
@@ -762,16 +762,16 @@ export function removeSlice(array: any[], slice: any[]) {
...
-  message: string
-  type: "confirm" | "list" | "input"
-  default?: any
-  choices?: string[]
-  pageSize?: number
-}): Promise<any> {
-  const inquirer = await import("inquirer")
-  return inquirer.prompt(params)
+export async function userPrompt(params: { message: string; type: "confirm" | "input"; default?: any }): Promise<any> {
+  const { confirm, input } = await import("@inquirer/prompts")
```
Comment (stefreak) [inline core/src/util/util.ts:766]: @vvagaytsev I think it'd be good to cover this in a unit test, so we notice if the package name changes next time.
It's a good practise to add regression tests like this. The unit test can be quite minimal because it only needs to cover the import issue that we experienced here. This avoids us having the same issue again, next time the package name changes.

Comment (vvagaytsev) [reply core/src/util/util.ts:766]: Right, @stefreak. Good point! I'm wondering if we can just use eager imports instead.
Let's see how slow the eager imports are. I'll keep an eye on it on the next `inquirer` lib update.
