### PR TITLE
fix: cleanup-cluster-registry script fails to run

### LINKED ISSUE #1041: `cleanup-cluster-registry` fails with "Cannot read property 'map' of null"
### Current Behavior

The command runs, but exits partway through, and no space is freed.

```
[eronarn@ip-192-168-10-243 qf]$ garden plugins kubernetes cleanup-cluster-registry --logger-type=basic --log-level=5
Loading plugin exec
Loading plugin container
Loading plugin kubernetes
Done loading plugin exec
Done loading plugin container
Done loading plugin kubernetes
Emit event 'taskPending'
Emit event 'taskPending'
Emit event 'taskPending'

TaskGraph: this.index before processing
---------------------------------------
resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c:
  id: resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c
  dependencies: []
resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c:
  id: resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c
  dependencies: []
resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c:
  id: resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c
  dependencies: []

Emit event 'taskGraphProcessing'
Processing tasks...
ℹ Remaining tasks 3
Currently in progress [resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c, resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c, resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c]
ℹ tasks                     → Processing task resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c
Currently in progress [resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c, resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c, resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c]
ℹ tasks                     → Processing task resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c
Currently in progress [resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c, resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c, resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c]
ℹ tasks                     → Processing task resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c
Currently in progress [resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c, resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c, resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c]
Emit event 'taskProcessing'
Emit event 'taskProcessing'
Emit event 'taskComplete'
✔ tasks                     → Completed task resolve-provider.exec.cd97ef40-b213-11e9-8cb3-7f2021806c2c (took 0.008 sec)
ℹ Remaining tasks 2
Emit event 'taskComplete'
✔ tasks                     → Completed task resolve-provider.container.cd97ef41-b213-11e9-8cb3-7f2021806c2c (took 0.009 sec)
ℹ Remaining tasks 1
Emit event 'taskProcessing'
Calling configureProvider on kubernetes
Emit event 'taskComplete'
✔ tasks                     → Completed task resolve-provider.kubernetes.cd97ef42-b213-11e9-8cb3-7f2021806c2c (took 0.016 sec)
ℹ Remaining tasks 0
ℹ Remaining tasks 0
Emit event 'taskGraphComplete'
ℹ Cleaning up old workspaces from build sync volume...
   Running: kubectl exec -i garden-build-sync-558bcc7f65-58bxj -- sh -c stat /data/* -c "%n %X"
   Deleting 0 workspace directories.
   Running: kubectl exec -i garden-build-sync-558bcc7f65-58bxj -- rm -rf
✔ Cleaning up old workspaces from build sync volume...
ℹ Scanning all Pods in the cluster...
   Found 60 images in use in cluster, 1 referencing the in-cluster registry.
✔ Scanning all Pods in the cluster...
ℹ Listing all images in cluster registry...
   Forwarding local port 52112 to Deployment/garden-docker-registry container port 5000
   Running 'kubectl port-forward Deployment/garden-docker-registry 52112:5000'
   [Deployment/garden-docker-registry port forwarder] Forwarding from 127.0.0.1:52112 -> 5000

   [Deployment/garden-docker-registry port forwarder] Forwarding from [::1]:52112 -> 5000

   [Deployment/garden-docker-registry port forwarder] Handling connection for 52112

   Reusing local port 52112 for Deployment/garden-docker-registry container
   [Deployment/garden-docker-registry port forwarder] Handling connection for 52112

Cannot read property 'map' of null

See error.log for detailed error message
 Listing all images in cluster registry...
```

Tail of the error.log:

```
stderr: >
  failed to copy files: failed to copy directory: Error processing tar file(exit
  status 1): open /app/assets/images/icons/icon-back-hover.svg: no space left on
  device

  command terminated with exit code 1
failed: true
signal: null
cmd: >-
  /Users/eronarn/.garden/tools/kubectl/52606cbad4c7babc/kubectl
  --context=stg-admin@staging --namespace=garden-system exec -i
  garden-docker-daemon-7ffbfb6f8b-xw94q -c docker-daemon -- docker build -t
  127.0.0.1:5000/staging/qf:v-1bc2844862 -f
  /garden-build/84090d97-2594-46ca-b625-127e7824830f/qf/Dockerfile
  /garden-build/84090d97-2594-46ca-b625-127e7824830f/qf/ --build-arg
  REDACTED
timedOut: false
killed: false


[2019-07-29T15:16:19.956Z] TypeError: Cannot read property 'map' of null
    at /snapshot/dist/build/src/plugins/kubernetes/commands/cleanup-cluster-registry.js:0
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/dist/build/src/plugins/kubernetes/commands/cleanup-cluster-registry.js:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Expected behavior

The command successfully prunes the managed volume.

### Your environment

```
[eronarn@ip-192-168-10-243 qf]$ garden version && kubectl version && docker version
0.10.2
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f97efcc
 Built:             Wed Jun  5 01:37:53 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       f97efcc
  Built:            Wed Jun  5 01:42:10 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by 10ko**
**What this PR does / why we need it**:
The cleanup script was hanging or simply not working. 
Specifically it would crash whenever it tried to delete images from a repo with no available tags.
Another issue occurred whenever the docker-daemon had too many images to delete and reached the maximum lenght of arguments for the delete command. 
This PR fixes those bugs. 

**Which issue(s) this PR fixes**:

Fixes #1041 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts [hunk 1]
```diff
@@ -292,9 +292,15 @@ async function deleteImagesFromDaemon(provider: KubernetesProvider, log: LogEntr
   if (imagesToDelete.length === 0) {
     log.info(`Nothing to clean up.`)
   } else {
-    log.info(`Cleaning up ${imagesToDelete.length} images...`)
-    const args = ["docker", "rmi", ...imagesToDelete]
-    await execInBuilder({ provider, log, args, podName, timeout: 300 })
+    let counter = imagesToDelete.length
+    log.info(`Cleaning up ${counter} images...`)
+
+    await Bluebird.map(imagesToDelete, async (image) => {
```
Comment (eysi09) [inline garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts]: Just thinking out loud here but would it be better to batch this instead spawning all these `execInBuillder` processes? Since there are potentially thousands of images right? So something like `const args = ["docker", "rmi", "aBatchOfOneHundredImages"]`. (cc @thsig)

Comment (edvald) [reply garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts]: That's how it was before. @10ko what was the reason for this change?

Comment (10ko) [reply garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts]: Hi @edvald, if you look at the diff we didn't do batching before, we were just running `docker rmi` once appending all the images as parameter. That was causing an error becuase in case of thousands of images, we reached the OS limit for the lenght of a command. I agree though that just crating thousands of promises might not be very smart.
I updated the code and it now first splits the images in batches of 100 and then I added a limit in concurrency when we call`Bluebird.map(...)`.
We can still tweak the two numbers but I think it's quite reasonable for now. 
Let me know what you think. 
E.

File: garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts [hunk 2]
```diff
@@ -292,9 +292,22 @@ async function deleteImagesFromDaemon(provider: KubernetesProvider, log: LogEntr
   if (imagesToDelete.length === 0) {
     log.info(`Nothing to clean up.`)
   } else {
-    log.info(`Cleaning up ${imagesToDelete.length} images...`)
-    const args = ["docker", "rmi", ...imagesToDelete]
-    await execInBuilder({ provider, log, args, podName, timeout: 300 })
+    const batch = 100
+    const imagesBatches: string[][] = []
+    for (let i = 0; i < imagesToDelete.length; i += batch) {
```
Comment (eysi09) [inline garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts]: You could also use `lodash`'s `chunk` function for this.
