### PR TITLE
Fix logs

### LINKED ISSUE #1246: Logs stop loading after hot reload event
### Current Behavior

Logs stop loading after a hot reload event. This is because Garden looks for the pod with the latest content hash version but the pod hasn't been redeployed in the cluster (because hot reload).

See this comment for details: https://github.com/garden-io/garden/issues/1226#issuecomment-535222652

### PR DESCRIPTION
**Pull request by eysi09**
**What this PR does / why we need it**:

This fixes an issue where Garden wouldn't find pods because the version in
the cluster didn't match the version Garden expected after a hot reload
event. This would e.g. cause issues for the 'logs' and 'exec' commands.

**Which issue(s) this PR fixes**:

Fixes #1246 (and an undocumented issue where `garden exec my-module <cmd>` wouldn't work after a hot reload event).

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/util.ts [hunk 1]
```diff
@@ -79,10 +79,34 @@ export function getSelectorFromResource(resource: KubernetesWorkload) {
...
+    .uniqBy((pod) => JSON.stringify(pod.metadata.labels))
+    .value()
+  return sortBy([...uniqByLabel, ...noLabel], (pod) => pod.metadata.creationTimestamp)
+}
+
+/**
+ * Retrieve a list of pods based on the resource selector, deduplicated so that only the most recent
+ * pod is returned when multiple pods with the same label are found.
+ */
+export async function getDeduplicatedWorkloadPods(api: KubeApi, namespace: string, resource: KubernetesWorkload) {
```
Comment (edvald) [inline garden-service/src/plugins/kubernetes/util.ts]: "Deduplicated" is maybe slightly odd naming, since the Pods won't be duplicated as such. How about `getMostRecentWorkloadPods` or `getCurrentWorkloadPods`?
