### PR TITLE
fix(watcher): native fsevents were not used in dist build on macOS

### LINKED ISSUE #1077: High CPU usage while running "garden dev"
### Current Behavior

Screenshot 2019-08-06 at 08 25 55

### Expected behavior

I don't expect the CPU usage to be so high when no files are being changed.

### Reproducible example

I've got a working repository at [ThePixelDeveloper/SitemapBundleExample](https://github.com/ThePixelDeveloper/SitemapBundleExample)

### Workaround

n/a

### Suggested solution(s)

A more efficient watcher library.

### Additional context

n/a

### Your environment

`garden version`

```
❯ garden version
0.10.3
```

`kubectl version`

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`

```
❯ docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by edvald**
**What this PR does / why we need it**:

This bug caused a tremendous slowdown and high CPU usage on Mac. The fix is
essentially to use a newer version of Pkg for macOS (but not for other
builds because the newer version breaks other platforms, yay), as well
as to update the fsevents binary.

I've also put in an assertion to try to prevent this happening again
without us noticing.

Fixes #1077

### CODE REVIEW

File: garden-service/src/watch.ts [hunk 1]
```diff
@@ -82,6 +83,18 @@ export class Watcher {
     this.log.debug(`Watcher: Watching paths ${this.paths.join(", ")}`)
 
     if (watcher === undefined) {
+      // Make sure that fsevents works when we're on macOS. This has come up before without us noticing, which has
+      // a dramatic performance impact, so it's best if we simply throw here so that our tests catch such issues.
+      if (process.platform === "darwin") {
```
Comment (elliott-davis) [inline garden-service/src/watch.ts]: I like this idea

**Comment by edvald** [comment]
Lol, yeah that's pretty much how I felt when I saw it finally working. Odd class of bug indeed o_o.

File: garden-service/bin/build-pkg.sh [hunk 2]
```diff
@@ -43,43 +43,55 @@ rsync -r --exclude=.garden --exclude=.git static tmp/dist
...
+
+echo "  -> macos-amd64"
+rm -rf macos-amd64
+mkdir macos-amd64
+
+# Need to use a newer version of Pkg for the fsevents module to work properly,
+# which unfortunately does NOT work for other platforms :/
+echo "    -> install pkg@4.4.0"
+npm init -y
+npm install pkg@4.4.0
```
Comment (eysi09) [inline garden-service/bin/build-pkg.sh]: Should we reset `pkg` to the `package.json` when this finishes so that the script leaves the `node_modules` as they were when we're running this locally? So that we don't run into issues when we test the script locally.

Comment (edvald) [reply garden-service/bin/build-pkg.sh]: This is performed in the `dist` directory, so it doesn't affect the `garden-service` package.

**Comment by edvald** [comment]
We should make sure to test the CI generated edge binaries once they're built. For reference, I could reproduce the reported CPU usage issue by simply running Garden in a project with a large number of files (e.g. with a fairly large node_modules folder).
