### PR TITLE
fix: allow relative symlinks to directories when using build staging

### LINKED ISSUE #2382: "Attempted to copy non-file" when a symlink target is a folder
## Bug

Building breaks when a module contains a symlink to a folder.

The offending line only checks if the target of a symlink is a file, but doesn't check if it's a folder.

https://github.com/garden-io/garden/blob/893e55b6e4932dda671509248ce2acf513eb8526/core/src/build-staging/helpers.ts#L68

### Current Behavior

An error of "Attempted to copy non-file" is raised.

### Expected behavior

The build will be successful.

### Reproducible example

Projects that contain a symlink to a folder.

### Suggested solution(s)

Add a condition that checks if the target is a folder and if so don't raise an error.

### Your environment

* **OS:** macOS BigSur 11.3
* **How I'm running Kubernetes:** Docker Desktop

`garden version`
0.12.21

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:

Allows using relative symlinks to directories and files when using build staging.

The goal is to reproduce symlinks in the target directory as-is, without having to resolve them.
The user would be responsible for making sure that both the relative symlink as well as the target
directory are included in the action.

If the symlink points to a file or directory outside the actions's source path, this throws an
error.

To avoid this becoming a breaking change, we keep the old behaviour if the symlink points to a
file. In that case, we resolve the symlink and copy the target file. If the target file is outside
 the action's source or build directory, log a warning.

In a future 0.14 release of Garden, we should remove that branch, only reproduce symlinks (without
resolving them recursively) and
throw an error if the link is out of bounds.

**Which issue(s) this PR fixes**:

Fixes #2382

### CODE REVIEW

File: core/src/build-staging/helpers.ts [hunk 1]
```diff
@@ -6,22 +6,27 @@
...
 import { promisify } from "util"
+import { styles } from "../logger/styles.js"
+import { emitNonRepeatableWarning } from "../warnings.js"
+import { type Log } from "../logger/log-entry.js"
 
 export type MappedPaths = [string, string][]
 
 export interface CloneFileParams {
+  log: Log
+  root: string
```
Comment (vvagaytsev) [inline core/src/build-staging/helpers.ts:29]: Minor nit. Should we call this `sourceRoot`? Root sounds a bit broad.

**Review by vvagaytsev — DISMISSED** [review]
Looks good, thank you! 👍 
Left a couple of non-blocking comments.

**Review by thsig — DISMISSED** [review]

**Comment by vvagaytsev** [comment]
@stefreak I've addressed the suggested changes in the recent refactoring commits.

Can you please take a look and review those changes? Just to be sure I haven't mixed up anything when I transformed positional arguments to a parameter object in the `ResolveSymlinkCallback`.

File: core/src/build-staging/build-staging.ts [hunk 2]
```diff
@@ -189,7 +189,7 @@ export class BuildStaging {
 
     // Source root must exist and be a directory
     let sourceStat = await statsHelper.extendedStat({ path: sourceRoot })
-    if (!sourceStat || !(sourceStat.isDirectory() || sourceStat.target?.isDirectory())) {
+    if (!sourceStat || !sourceStat.isDirectory()) {
```
Comment (stefreak) [inline core/src/build-staging/build-staging.ts:192]: I think this one must have been an accident
```suggestion
    if (!sourceStat || !(sourceStat.isDirectory() || sourceStat.target?.isDirectory())) {
```

**Review by stefreak — COMMENTED** [review]
I can't approve your changes @vvagaytsev but it looks ok to me! The callback-style code is in dire need of refactoring to promises & async/await but for now this seems good enough to me.

**Review by vvagaytsev — APPROVED** [review]

**Comment by vvagaytsev** [comment]
Thanks @stefreak! I've put a formal approval on it :)
