### PR TITLE
 fix(provider): allow initialising providers without write ops for validation command

### LINKED ISSUE #6029: Running `garden validate` applies terraform `rootStack` when `autoApply` is set to true
### Current Behavior

When running `garden validate` with a terraform `rootStack` that has `autoApply` set to true, the stack gets applied. 

### Expected behavior

A validate command should not apply changes to infrastructure even when `autoApply` is set.

### Reproducible example

https://github.com/garden-io/garden/tree/main/examples/terraform-gke

### Your environment

* **OS:**  macOS
* **How I'm running Kubernetes:** 

`garden version`
0.13.30

### PR DESCRIPTION
**Pull request by twelvemo**
**What this PR does / why we need it**:

While resolving providers all kinds of actions are performed in the different providers e.g. for the kubernetes providers ingress controllers are installed and app namespaces created. The terraform provider with an `initRoot` stack and `autoApply` set to `true` will even apply a terraform stack on provider initialization. This is the intended behavior for a lot of commands like `deploy` etc. However some commands like `validate` also rely on resolving the providers, whereas a `validate` command should not apply any changes.

This PR adds a `statusOnly` param to the graph and provider resolution so providers can be resolved and their status queried without any write operations. To do this the `getEnvironmentStatus` handler on each provider should only implement status checks, while the `prepareEnvironment` handler should handle any write calls. Added tests for all providers that implement these handlers.

**Which issue(s) this PR fixes**:

Fixes #6029 #3327

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/tasks/resolve-provider.ts [hunk 1]
```diff
@@ -379,7 +380,7 @@ export class ResolveProviderTask extends BaseTask<Provider> {
     await writeFile(cachePath, serialize(cachedStatus))
   }
 
-  private async ensurePrepared(tmpProvider: Provider) {
+  private async ensurePrepared(tmpProvider: Provider, statusOnly?: boolean) {
```
Comment (vvagaytsev) [inline core/src/tasks/resolve-provider.ts:383]: Argument `statusOnly` can be declared as non-optional here. This method is called from only one place, and the actual non-optional boolean value is supplied.

File: core/src/graph/solver.ts [hunk 2]
```diff
@@ -418,7 +418,7 @@ export class GraphSolver extends TypedEventEmitter<SolverEvents> {
           // Status is either aborted or failed
           this.log.silly(() => `Request ${request.getKey()} status: ${resultToString(status)}`)
           this.completeTask({ ...status, node: request })
-        } else if (request.statusOnly && status !== undefined) {
+        } else if (request.statusOnly && status !== undefined && status.result) {
```
Comment (vvagaytsev) [inline core/src/graph/solver.ts:421]: Is the condition `status.result` necessary here? The `GraphResult.result` field is defined as nullable. I'm not sure about the semantics behind the `null`-value here.

File: core/src/garden.ts [hunk 3]
```diff
@@ -742,7 +742,7 @@ export class Garden {
   @OtelTraced({
     name: "resolveProviders",
   })
-  async resolveProviders(log: Log, forceInit = false, names?: string[]): Promise<ProviderMap> {
+  async resolveProviders(log: Log, forceInit = false, statusOnly = false, names?: string[]): Promise<ProviderMap> {
```
Comment (vvagaytsev) [inline core/src/garden.ts:745]: We can now convert the args list to a param object. Maybe we should do the same for `resolveProvider(...)` method.

File: core/test/integ/src/plugins/kubernetes/provider.ts [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+import { getEnvironmentStatus, prepareEnvironment } from "../../../../../src/plugins/kubernetes/init.js"
+import type { PrepareEnvironmentParams } from "../../../../../src/plugin/handlers/Provider/prepareEnvironment.js"
+import type { Garden } from "../../../../../src/index.js"
+
+async function ensureNamespaceDoesNotExist(api: KubeApi, namespaceName: string) {
+  try {
+    await api.core.readNamespace({ name: namespaceName })
+  } catch (e) {
+    return
+  }
```
Comment (vvagaytsev) [inline core/test/integ/src/plugins/kubernetes/provider.ts:25]: Could this be simplified with `namespaceExists` helper?

Something like
```js
if (!(await namespaceExists(api, namespaceName))) {
    return
}
```

**Review by vvagaytsev — COMMENTED** [review]
Looks good, thank you! 👍 

I've left [one question](https://github.com/garden-io/garden/pull/6051/files#r1607826922) and a few non-blocking minor comments. Let's check those and get this merged today.

Huge thanks for adding provider-level tests! 💯

File: core/src/graph/solver.ts (hunk 2 above)
Comment (twelvemo) [reply core/src/graph/solver.ts:421]: `statusOnly` wasn't really used before. Now when it is actually `true` and passed in to the solver, it will return a `status` in the first iteration, but `status.result` will still be `null`. However `status.result` is needed in `completeTask` see [here](https://github.com/garden-io/garden/blob/main/core/src/graph/solver.ts#L469).

Comment (twelvemo) [reply core/src/graph/solver.ts:421]: It is a bit confusing, but we actually try to read `result.result` [here](https://github.com/garden-io/garden/blob/main/core/src/graph/solver.ts#L469) which is still null after `complete`.
Without this check, garden crashes:
```
TypeError: Cannot read properties of null (reading 'status')
    at file:///Users/anna/repos/garden/core/build/src/garden.js:575:56
    at Array.every (<anonymous>)
    at file:///Users/anna/repos/garden/core/build/src/garden.js:575:41
```
Do you think there is a better way to deal with this?

Comment (vvagaytsev) [reply core/src/graph/solver.ts:421]: Ah, I see. Thanks for the clarification! 👍 
I don't see a better way at the moment, just wanted to double check this and get more context :)
Looks good!

**Review by vvagaytsev — APPROVED** [review]
Thank you! 💯
