### PR TITLE
0.12 backport: improvement: using new release endpoint for self-update

### LINKED ISSUE #4893: [Bug]: github API rate-limiting can occur in `garden self-update`
### Current Behavior

If github is seeing too many requests to the API from your IP address, for example if you're working in an office or using a company VPN with NAT, it'll rate limit your API calls.

In garden self-update this can look like this:
```
% garden self-update
Update Garden 🗞️

No installation directory specified via --install-dir option. Garden will be re-installed to the current installation directory: /opt/homebrew/Cellar/garden-cli/0.13.9/libexec
Checking for target and latest versions...

Response code 403 (rate limit exceeded)
```

### Expected behavior

I would expect garden self-update to "just work" even when using IP addresses that GitHub is rate limiting, or alternatively the error message should contain instructions how to update Garden manually or how to supply Github access token to work around the rate limit.

### Reproducible example

Not easy to reproduce,  but we know this can happen with unauthenticated requests to the GitHub api, e.g. https://github.com/garden-io/garden/blob/main/core/src/commands/self-update.ts#L98

Use the following example at your own risk (successfully reproduces the issue for me :))

```
#!/bin/bash
while true; do
  garden self-update &
  sleep 0.1
done
```

### Workaround

You can use the methods described in https://docs.garden.io/guides/installation to install the latest version of garden manually as a workaround.

### Suggested solution(s)

- Use the version-check service that we host server side, to provide latest version information to users. This service can cache the version information to reduce calls to the GitHub API and use an auth token to authenticate requests.
- Alternativels, improve the error message to instruct users how to update manually or allow users to specify their own github auth token (But I'd strongly vote for the first option instead of this)

### Your environment

* **OS:** all OSes (I'm using macos)
* **How I'm running Kubernetes:** irrelevant

`garden version` 0.13.9

### PR DESCRIPTION
**Pull request by mkhq**
**What this PR does / why we need it**:

This is a 0.12 backport of #5229. Tests and code are ported over. ARM support was excluded from the backport since its only available from 0.13.12.

**Which issue(s) this PR fixes**:

Fixes #4893 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by vvagaytsev** [comment]
@mkhq thanks for back-porting this! The docs need to be re-generated. The rest test failures and known and expected.

File: core/src/constants.ts [hunk 1]
```diff
@@ -47,8 +47,7 @@ export const SUPPORTED_ARCHITECTURES: SupportedArchitecture[] = ["x64", "arm64"]
 export const SEGMENT_DEV_API_KEY = "D3DUZ3lBSDO3krnuIO7eYDdtlDAjooKW" // ggignore
 export const SEGMENT_PROD_API_KEY = "b6ovUD9A0YjQqT3ZWetWUbuZ9OmGxKMa" // ggignore
 
-export const DOCS_BASE_URL = "https://docs.garden.io/v/acorn-0.12"
-export const VERSION_CHECK_URL = "https://get.garden.io/version"
+export const DOCS_BASE_URL = "https://docs.garden.io"
```
Comment (vvagaytsev) [inline core/src/constants.ts:50]: This must be `DOCS_BASE_URL = "https://docs.garden.io/v/acorn-0.12"` in the `0.12` branch.

**Review by vvagaytsev — APPROVED** [review]
Thank you! 👍
