### PR TITLE
fix(pulumi): return correct responses for pulumi plugin commands

### LINKED ISSUE #5084: 0.13: [Bug]: Failed to recognize state when pulumi identified no resources changed
### Current Behavior

garden is failing to recognize the state when pulumi identified no resources available to change.

`Failed to Deploy type=pulumi name=x-service (from module x-service): Error: Deploy type=pulumi name=x-service (from module x-service) failed: TypeError: Cannot read properties of null (reading 'state')`

Command `garden plugins pulumi preview` 

### Expected behavior
garden should executed the command successfully without throwing an error.

Reference project
https://github.com/ishantagarwal-x213235/garden-sample-project

### LINKED ISSUE #5118: Crash: Cannot read properties of null (reading 'state')
### Error message

```console
$ garden --env=dev plugins pulumi preview
Plugins 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev.garden-dev-salotz
Running pulumi preview for actions  

ℹ providers            → Getting status...
✔ providers            → Cached (took 0 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ providers            → Getting status...
✔ providers            → Cached (took 0 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 2.2 sec)

ℹ deploy.test-data-sa  → Running pulumi preview
ℹ deploy.test-data-sa  → No resources were changed in the generated plan for deploy.test-data-sa.
✔ deploy.test-data-sa  → Success (took 7.7 sec)
✖ deploy.test-data-sa  → Failed processing Deploy type=pulumi name=test-data-sa (took 7.7 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20Cannot%20read%20properties%20of%20null%20(reading%20%27state%27)

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed processing Deploy type=pulumi name=test-data-sa (took 7.7 sec). This is what happened:
TypeError: Cannot read properties of null (reading 'state')
    at ProcessTaskNode.execute (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/nodes.js:214:31)
    at async GraphSolver.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/solver.js:282:35)
──────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed to Deploy type=pulumi name=test-data-sa: Error: Deploy type=pulumi name=test-data-sa failed: Error: Cannot read properties of null (reading 'state')
```

### Your environment

* **OS: linux** 
* **How I'm running Kubernetes: GKE** 
* **Garden version: garden version: 0.13.14** 

### Frequency

It happens every time I run the command.

### Workaround

I don't really need this command so not a big deal.

### PR DESCRIPTION
**Pull request by shumailxyz**
**What this PR does / why we need it**:
This enforces responses of type ValidResultType for the pulumi plugin commands for actions. Previously, the plugin commands for actions were not returning anything, resulting in runtime errors. The TS compiler didn't catch these due to the pulumi plugin command responses typed as `any`.
**Which issue(s) this PR fixes**:

Fixes #5118
Fixes #5084

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/graph/nodes.ts [hunk 1]
```diff
@@ -273,7 +273,7 @@ export class ProcessTaskNode<T extends Task = Task> extends TaskNode<T> {
     try {
       const processResult: TaskResultType<T> = await this.task.process({ status, dependencyResults, statusOnly: false })
       this.task.emit("processed", { result: processResult })
-      if (processResult.state === "ready") {
+      if (processResult?.state === "ready") {
```
Comment (stefreak) [inline core/src/graph/nodes.ts:276]: If it's ok that task.process returns undefined, then we need to change it's return type signature

**Review by stefreak — APPROVED** [review]
Awesome work @shumailxyz!

I'd love to see tests for this, but as the pulumi provider is still flagged as experimental I am ok with this as-is; it's already a big improvement and will help catch this class of bugs during compilation.

**Comment by shumailxyz** [comment]
Totally agreed. We have a separate issue https://github.com/garden-io/garden/issues/4600 to track tests for pulumi, should consider prioritizing that.
