### PR TITLE
docs: fix action kind rendering in reference docs

### LINKED ISSUE #4056: 0.13: [Bug]: Reference docs on Action types are missing context; config keys not alphabetically sorted
### Current Behavior

Garden's Action Types reference page is missing context: it is unclear which Action (Build, Deploy, Run, Test) each `kind`  block sits under.

image

Additionally, config keys in the sidebar of each kind's action are not alphabetically sorted. If this is by design, please disregard.

image

This bug is submitted on behalf of @pepov and has been validated by @worldofgeese. @pepov may have addditional context to share.

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:

* [x] fix action kind rendering
* [ ] ~ensure alphabetical sorting of the configuration keys~

**Which issue(s) this PR fixes**:

Partially fixes #4056

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/docs/generate.ts [hunk 1]
```diff
@@ -110,7 +110,7 @@ export async function writeConfigReferenceDocs(docsRoot: string, plugins: Garden
   const actionTypeDefinitions = await garden.getActionTypes()
 
   for (const [kind, types] of Object.entries(actionTypeDefinitions)) {
-    actionsReadme.push(`* \`kind\``)
+    actionsReadme.push(`* ${kind}`)
```
Comment (vvagaytsev) [inline core/src/docs/generate.ts:113]: Should this be an active hyperlink?

**Review by edvald — APPROVED** [review]

File: core/src/docs/generate.ts (hunk 1 above)
Comment (vvagaytsev) [reply core/src/docs/generate.ts:113]: Ah, it's just a grouping by kind. There are no pages to refer to :)
