### PR TITLE
fix(git): error when running before first commit is made in repo (#324)

### LINKED ISSUE #324: Garden doesn't work until the first commit has been made
Fails with:

```
Command failed: git diff-index --name-only HEAD /Users/eysi/code/garden-io/sock-shop/services/front-end
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### PR DESCRIPTION
**Pull request by edvald**
Closes #324

### CODE REVIEW

File: garden-service/src/vcs/git.ts [hunk 1]
```diff
@@ -60,17 +60,31 @@ export class GitHandler extends VcsHandler {
...
+    } catch (err) {
+      if (err.code === 128) {
+        // no commit in repo, use default version
+        commitHash = NEW_MODULE_VERSION
+      } else {
+        throw err
+      }
+    }
+
+    const newFiles = (await git("ls-files", ["--other", "--exclude-standard", path])).split("\n")
```
Comment (drubin) [inline garden-service/src/vcs/git.ts]: Will this not need to be put in a try catch too?
