### PR TITLE
fix(k8s): add imagePullSecret from kubernetes provider to sync init container

### LINKED ISSUE #6525: [Bug]: Image pull secrets not set on sync util pod causing Dockerhub rate limiting
### Current behavior

Due to #5336, users can get rate limited when pulling Garden images from our public Dockerhub repo if they haven't added an image pull secret with their Docker credentials to their cluster. Admittedly they shouldn't need that in the first place and we are applying for the "Docker Verified Publisher" program which should fix this.

Adding the secret fixes the issue for some of the util pods but not for the sync pod because the image pull secrets aren't set in its manifest. 

We need to fix that for now, although again, if/when we're a verified publisher it shouldn't be needed in the first place.

### Expected behavior

Creating the sync util pod shouldn't fail with a Dockerhub rate limit error if the user already has created image pull secrets and specified in the Garden config (under the K8s provider `imagePullSecrets` field).

### Reproducible example

N/A

### Workaround

N/A

### Suggested solution(s)

We should set the `imagePullSecrets` on the sync util Deployment like we e.g. do for the buildkit Deployment here: https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/container/build/buildkit.ts#L218

### PR DESCRIPTION
**Pull request by twelvemo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #6525

**Special notes for your reviewer**:

### CODE REVIEW

**Review by eysi09 — DISMISSED** [review]
Looks great but I think there's some issue with Prettier, just bumped into the same. 

Locally it fails if there's that extra parenthesis, but in CI it fails if it's not there 🙃

File: core/src/plugins/kubernetes/sync.ts [hunk 1]
```diff
@@ -334,7 +334,7 @@ export async function configureSyncMode({
           Override configuration:
           ${(override.command?.length ?? 0) > 0 ? `Command: ${override.command?.join(" ")}` : ""}
           ${(override.args?.length ?? 0) > 0 ? `Args: ${override.args?.join(" ")}` : ""}
-          ${(override.image?.length ?? 0) ? `Image: ${override.image}` : ""}
+          ${override.image?.length ?? 0 ? `Image: ${override.image}` : ""}
```
Comment (vvagaytsev) [inline core/src/plugins/kubernetes/sync.ts:337]: This causes the [lint failure](https://app.circleci.com/jobs/github/garden-io/garden/567290) because we switched to `prettier 3.3.3` in #6500.

**Comment by vvagaytsev** [comment]
@eysi09 @twelvemo just run `npm i` locally to get the latest `prettier` from #6500 :)

**Comment by eysi09** [comment]
> @eysi09 @twelvemo just run `npm i` locally to get the latest `prettier` from #6500 :)

Ah right, I did that but hadn't pulled latest main. Didn't realise it was that recent a change.

**Comment by twelvemo** [comment]
Thanks for the hint with the linter! Also should've added the imagePullSecret to the pod and not the container spec. Importing the type for the container spec will make sure there is no confusion here again.
