### PR TITLE
fix(core): ensure deletes are synced when staging builds

### LINKED ISSUE #1278: Deleted files not removed from .garden/build directory
### Current Behavior

Deleted are not synced to the build directory, meaning files stay there even after they're deleted from the project proper. 

### Expected behavior

Deleting a project file should also remove it from the build directory, next time Garden stages a build.

### Workaround

Delete the module build directory: `rm -rf .garden/build/my-module`

### LINKED ISSUE #1314: It's possible to sync folders while having stale contents
### Current Behavior

Saving modifications to my Helm chart wasn't resulting in updates in Garden with this config file:
```
kind: Module
name: data-depot-metadata-chart
type: helm

timeout: 180

# this forces only watching the Chart files
include:
  - helm-chart/data-depot-metadata/*

# which directory to treat as the chart
chartPath: helm-chart/data-depot-metadata
```
```
ℹ data-depot-metadata-chart → Preparing build (3 files)...
ℹ data-depot-metadata-chart → Getting build status for v-c23da46254...
ℹ data-depot-metadata-chart → Building version v-c23da46254...
✔ data-depot-metadata-chart → Building version v-c23da46254... → Done (took 0.1 sec)
```

I realized that the globbing was possibly only testing the _folder_ and not recursively updating the files. That did fix it:
```
kind: Module
name: data-depot-metadata-chart
type: helm

timeout: 180

# this forces only watching the Chart files
include:
  - helm-chart/data-depot-metadata/**

# which directory to treat as the chart
chartPath: helm-chart/data-depot-metadata
```
```
ℹ data-depot-metadata-chart → Preparing build (12 files)...
ℹ data-depot-metadata-chart → Getting build status for v-5f3538ad69...
ℹ data-depot-metadata-chart → Building version v-5f3538ad69...
✔ data-depot-metadata-chart → Building version v-5f3538ad69... → Done (took 0 sec)
```

I believe this is also related to https://github.com/garden-io/garden/issues/1278 where I ran it with the correct glob once, then broke it, and then had files stuck afterwards.

### Expected behavior

If I only sync a folder, anything underneath it is deleted, rather than stale content being present.

### Your environment

```
0.10.13
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

### PR DESCRIPTION
**Pull request by edvald**
**What this PR does / why we need it**:

Due to our mishandling/misunderstanding of rsync behavior (see
https://stackoverflow.com/questions/1813907), deleted files would
linger in the build staging directory.

**Which issue(s) this PR fixes**:

Fixes #1278
Fixes #1314

### CODE REVIEW

File: garden-service/src/build-dir.ts [hunk 1]
```diff
@@ -174,12 +171,28 @@ export class BuildDir {
...
+        input = "/**/\n" + files.join("\n")
+      }
+    } else if (files !== undefined) {
       syncOpts.push("--files-from=-")
-      files = files.sort()
       input = files.join("\n")
+    }
+
+    // Avoid rendering the full file list except when at the silly log level
+    if (log.root.level === LogLevel.silly) {
```
Comment (eysi09) [inline garden-service/src/build-dir.ts]: Isn't that what `log.silly` does? Or is this to prevent it from being added to the log graph at all?

File: garden-service/test/unit/src/build-dir.ts [hunk 2]
```diff
@@ -50,40 +50,58 @@ describe("BuildDir", () => {
...
-    await garden.buildDir.syncFromSrc(moduleA, garden.log)
-    const buildDirA = await garden.buildDir.buildPath(moduleA)
+      await garden.buildDir.syncFromSrc(moduleA, garden.log)
+      const buildDirA = await garden.buildDir.buildPath(moduleA)
+
+      expect(await pathExists(await getConfigFilePath(buildDirA))).to.eql(true)
+      expect(await pathExists(join(buildDirA, "some-dir", "some-file"))).to.eql(false)
+    })
+
+    it("should delete files that are not being synced from the module source directory", async () => {
```
Comment (eysi09) [inline garden-service/test/unit/src/build-dir.ts]: Do we need a test for the case when files is `undefined`?

Comment (edvald) [reply garden-service/test/unit/src/build-dir.ts]: I considered that, but it doesn't actually come up anywhere.

File: garden-service/src/build-dir.ts (hunk 1 above)
Comment (edvald) [reply garden-service/src/build-dir.ts]: Without the explicit if-statement, the string is evaluated no matter what. And if it's thousands of lines, that's needless overhead.
