### PR TITLE
fix(k8s): fix type error when Kubernetes is not running

### LINKED ISSUE #784: Cannot read property 'output' of undefined when Kubernetes not running
### Current Behavior

Garden fails ungracefully with `Cannot read property 'output' of undefined` if Kubernetes cluster not running.

### Expected behavior

Should give a better error example.

### Reproducible example

Run `garden deploy` for a local env with Minikube / Docker for Desktop turned off.

### Workaround

N/A

### Suggested solution(s)

Here's the offending code: https://github.com/garden-io/garden/blob/master/garden-service/src/plugins/kubernetes/namespace.ts#L129

The `detail` key is not defined on the `err` object.

### Your environment

Latest `master`

### PR DESCRIPTION
**Pull request by eysi09**
Fixes #784

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/namespace.ts [hunk 1]
```diff
@@ -126,13 +126,13 @@ export async function prepareNamespaces({ ctx, log }: GetEnvironmentStatusParams
     await kubectl.exec({ log, context: kubeContext, args: ["version"] })
   } catch (err) {
     // TODO: catch error properly
-    if (err.detail.output) {
+    if (err) {
```
Comment (edvald) [inline garden-service/src/plugins/kubernetes/namespace.ts]: This will always be true...

File: garden-service/src/plugins/kubernetes/namespace.ts [hunk 2]
```diff
@@ -126,13 +126,13 @@ export async function prepareNamespaces({ ctx, log }: GetEnvironmentStatusParams
...
       throw new DeploymentError(
         `Unable to connect to Kubernetes cluster. ` +
         `Please make sure it is running, reachable and that you have the right context configured.`,
         {
           kubeContext,
-          kubectlOutput: err.detail.output,
+          kubectlOutput: err.stdout,
```
Comment (edvald) [inline garden-service/src/plugins/kubernetes/namespace.ts]: Probably should include stderr here too (fine to just concatenate).
