### PR TITLE
fix(remote-building): use "Recreate" strategy garden-util (kaniko) and garden-buildkit deployments

### LINKED ISSUE #2570: garden-util pods not found
### Current Behavior

On a fresh environment, nearly always the first run fails with this:
```
ℹ garden-util               → Resources ready
-> Deploying garden-util service in ci-116104942-eee536a0 namespace (was missing) → Done!
Failed building rust-workspace. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find a running Pod in Deployment garden-util
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Comparing expected and deployed resources...
All resources match.
Failed building python-poetry. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find a running Pod in Deployment garden-util
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Your environment

* **OS:** linux, gitlab runners
* **How I'm running Kubernetes:** AKS

```
Using docker image sha256:18a78542503a222ff1d128fd7abdf9fdae5e1f11dcfa9e17381da7ab4480776a for gardendev/garden-azure:0.12.25
```

### PR DESCRIPTION
**Pull request by stefreak**
We need to use the "[Recreate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment)" strategy for garden-util and garden-buildkit deployments, because
otherwise we can run into issues where multiple Pods are running at the same time

Also with the latest main I often get an error "Could not find a running Pod in Deployment garden-buildkit in namespace xxx" – this change fixes that too.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

e.g. Fixes #2570

**Special notes for your reviewer**:
The remote tests are covering this issue, but they are currently disabled in CI. Enabling them is out of scope for this PR, but will be addressed in #5103

### CODE REVIEW

File: core/src/plugins/kubernetes/container/build/buildkit.ts [hunk 1]
```diff
@@ -385,6 +385,11 @@ export function getBuildkitDeployment(
           app: buildkitDeploymentName,
         },
       },
+      strategy: {
+        // Note: When updating the deployment, we make sure to kill off old buildkit pods before new pods are started.
+        // This is important because with multiple running Pods we might end up syncing or building to the wrong Pod.
+        type: "Recreate",
```
Comment (TimBeyer) [inline core/src/plugins/kubernetes/container/build/buildkit.ts:391]: The PR says "Replace" but this says "Recreate". Which one is it? 😄

Comment (TimBeyer) [reply core/src/plugins/kubernetes/container/build/buildkit.ts:391]: You mean "Recreate"? 🙃

**Review by TimBeyer — APPROVED** [review]
