### PR TITLE
fix(cloud): handle tRPC errors in authentication functions

### LINKED ISSUE #7238: Crash: `TRPCClientError: fetch failed`
### Error message

```
Deploy 🚀

ℹ garden                    → Initializing...
ℹ garden-enterprise         → Authorizing...
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20TRPCClientError%3A%20fetch%20failed

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

TRPCClientError: fetch failed
    at TRPCClientError.from (file:///Users/magnus/Projects/garden/core/node_modules/@trpc/client/dist/TRPCClientError.mjs:53:16)
    at file:///Users/magnus/Projects/garden/core/node_modules/@trpc/client/dist/links/httpLink.mjs:79:52
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### What did you do?

after successfully logging in with `GARDEN_CLOUD_DOMAIN="https://<docker-compose dev instance>/"` g login, when I try to run `GARDEN_CLOUD_DOMAIN="https://<docker-compose dev instance>/"` g deploy I just get a crash. It should indicate the SSL verification failed instead, and not crash.

### Your environment

* **OS:** macOS
* **Garden version:** edge-cedar

### Frequency

Reproducable with docker-compose based dev backend

### Workaround

None (`NODE_TLS_REJECT_UNAUTHORIZED=0` should never be used for non-development purposes!)

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:

* Handle tRPC errors on calls via non-authenticated client
* Align auth error handling in between old and new backends
* Less confusing logging on logout

```console
You're already logged out from https://grow.garden.io.
Successfully logged out from https://grow.garden.io.
```
is now just
```console
You're already logged out from https://grow.garden.io.
```
and the sucessful message is printed only on successful token revocation.

**Which issue(s) this PR fixes**:

Fixes #7238

**Special notes for your reviewer**:

See individual commits for details.

### CODE REVIEW

**Comment by vvagaytsev** [comment]
Some tests failed. I converted it back to draft.

File: core/src/cloud/grow/trpc.ts [hunk 1]
```diff
@@ -80,3 +82,32 @@ export function getNonAuthenticatedApiClient(trpcConfigParams: Omit<TrpcConfigPa
 }
 
 export type ApiClient = CreateTRPCClient<AppRouter>
+
+export function isAggregateError(err: Error): err is AggregateError {
+  return err.constructor.name === "AggregateError"
+}
+
+export function describeTRPCClientError(err: TRPCClientError<InferrableClientTypes>) {
```
Comment (stefreak) [inline core/src/cloud/grow/trpc.ts:90]: Do you have some examples how some of these errors now look in practice? E.g. how does https://github.com/garden-io/garden/issues/7238 now get displayed?

Comment (vvagaytsev) [reply core/src/cloud/grow/trpc.ts:90]: @stefreak yes, it now looks like this:
```console
An error occurred while refreshing client auth token with Garden Enterprise: TRPCClientError: fetch failed; caused by: TypeError: fetch failed; caused by: Error: unable to verify the first certificate
Please try again.
```

Without the rendering function it would be just:
```console
An error occurred while refreshing client auth token with Garden Enterprise: fetch failed
Please try again.
```

Here the actual error message comes from the bottommost cause.

Comment (vvagaytsev) [reply core/src/cloud/grow/trpc.ts:90]: Printing the whole chain of the causes might look too technical, so maybe we should just print it on the debug level, and print a shortened variant in the error message.
Wdyt?

Comment (stefreak) [reply core/src/cloud/grow/trpc.ts:90]: Hm, maybe we can only display the nested message if the outer message is "fetch failed"? or we arrange the messages like so:

`fetch failed: unable to verify the first certificate`

Comment (vvagaytsev) [reply core/src/cloud/grow/trpc.ts]: I made it less verbose in the error messages in d72ef9df2bce7dd19875c5a14dfd5e26fd5e4148.
Now it satisfies the shape above (constructor names are omitted, and the error message chain is deduplicated).

The debug-level logs still print the detailed error description, that is calculated lazily.

**Review by stefreak — APPROVED** [review]
Awesome work!
