### PR TITLE
fix(k8s): use the same service account for pulling images as building

### LINKED ISSUE #5591: 0.13: [Bug]: `garden plugins kubernetes pull-image` does not work with IMDSv2 and hop limit of 1 (IRSA)
## Garden Bonsai (0.13) Bug

Garden pull image does not use existing buildkit or kaniko util container with IRSA policy.

### Current Behavior

If IMDSv2 with hop limit of 1 is used, the `garden plugins kubernetes pull-image` fails as it spawns a new util Pod without using the serviceAccount as necessary for IRSA to work. 

### Expected behavior

`pull-image` should simply succeed. This can be accomplished by using the existing util container instead of spawning a new one.

### Reproducible example

IRSA-enabled project

### Workaround
Unknown

### Suggested solution(s)

Don't spawn a new util container Pod for the skopeo pull command, but use the existing in-cluster-building util Pod.

https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/commands/pull-image.ts#L131

### Your environment

* **OS:** irrelevant
* **How I'm running Kubernetes:** AWS EKS

`garden version` 0.13.23

### PR DESCRIPTION
**Pull request by twelvemo**
**What this PR does / why we need it**:
The pull-image command spawns a pod for each image to pull. If you have set-up IRSA or Google Workload Identity for in-cluster building these pods also need to use the same service account as for in-cluster building.
**Which issue(s) this PR fixes**:

Fixes #5591

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/plugins/kubernetes/commands/pull-image.ts [hunk 1]
```diff
@@ -128,6 +128,14 @@ async function pullFromExternalRegistry({ ctx, log, localId, remoteId }: PullPar
     `docker-archive:${tmpTarPath}:${localId}`,
   ]
 
+  await ensureServiceAccount({
```
Comment (stefreak) [inline core/src/plugins/kubernetes/commands/pull-image.ts:131]: Instead of creating a new util deployment, could we instead use the existing methods to create a remote-building util deployment? Or can't we do this because it needs to work with local-docker too? 🤔

File: core/src/plugins/kubernetes/commands/pull-image.ts [hunk 2]
```diff
@@ -128,6 +128,14 @@ async function pullFromExternalRegistry({ ctx, log, localId, remoteId }: PullPar
...
+    ctx,
+    log,
+    api,
+    namespace,
+    annotations: ctx.provider.config.kaniko?.serviceAccountAnnotations,
```
Comment (stefreak) [inline core/src/plugins/kubernetes/commands/pull-image.ts:136]: What if the `buildMode` setting is `cluster-buildkit`?

File: core/src/plugins/kubernetes/commands/pull-image.ts (hunk 1 above)
Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: We create one util pod per pulled image. The image-pull command only allows pulling all your images at the same time, so it won't do to use an existing util deployment even if that exists.

File: core/src/plugins/kubernetes/commands/pull-image.ts (hunk 2 above)
Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: annotations can be undefined, then we create the service account spec without any annotations, see https://github.com/garden-io/garden/blob/010730cefb279de8dfc966afa43a0e8f704a3678/core/src/plugins/kubernetes/container/build/common.ts#L502

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: But what if the user is using buildkit, and specified the service account annotations there? I think we should call existing method to deploy util/build pods and then exec into the existing util container, instead of creating one just for pull-image.

Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: we always create the service account for `kaniko` and `cluster-buildkit`. For `cluster-buildkit` without any annotations.

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: Also, even if we support both modes in pull-image, it will be easy to overlook when we implement a new mode later.

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: Ah ok, cluster buildkit has no annotations? 🤔 Then I seem to misunderstand how IRSA works? 🤔 Shall we pair on this @twelvemo?

File: core/src/plugins/kubernetes/commands/pull-image.ts (hunk 1 above)
Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: Can't we run multiple commands in the same Pod using `exec`? What is the problem of re-using the same Pod? Are we worrying about filename collisions?

File: core/src/plugins/kubernetes/commands/pull-image.ts (hunk 2 above)
Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: Oh you are right, i misremembered of course we support cluster-buildkit for IRSA as well. Will push a fix.

File: core/src/plugins/kubernetes/commands/pull-image.ts (hunk 1 above)
Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: It is slow as is, distributing it via multiple pods and thereby nodes seems like a good idea.

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: Makes sense. If that's crucial, I suggest we re-use the same manifest definitions instead of duplicating the code, so we can't forget to update pull-image next time we make a change to util deployments.

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: At least we could move it to `common.ts`, so it lives next to the other manifests

Comment (twelvemo) [reply core/src/plugins/kubernetes/commands/pull-image.ts:131]: Yes that is a nice idea, however the util deplyoment from common is a deployment, while here we only spawn a pod that runs to completion.

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: I see there are differences, but they also have settings in common. Can we at least co-locate the code in the same file?

Comment (stefreak) [reply core/src/plugins/kubernetes/commands/pull-image.ts:136]: Looking at the code together, we agreed that it's enough to ensure that we always call `getBuilderServiceAccountAnnotations`, even from Kaniko and Buildkit.

**Review by stefreak — APPROVED** [review]
👍 Good work
