### PR TITLE
fix: prevent crash due to unresolved alias in yaml

### LINKED ISSUE #5186: Crash: Unresolved alias (the anchor must be set before the alias)
## Crash report

Garden crashes if a YAML anchor that's not defined is used. Here's an example config:

```
    clusterBuildkit:
      cache:
        - type: registry
          tag: _buildcache-main
          registry: *cacheRegistry # <-- This is not defined anywhere
```

### Error message

```
Encountered an unexpected Garden error. This is likely a bug :fallen_leaf:

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20Unresolved%20alias%20(the%20anchor%20must%20be%20set%20before%20the%20alias)%3A%20cacheRegistry

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

ReferenceError: Unresolved alias (the anchor must be set before the alias): cacheRegistry
    at Alias.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/Alias.js:42:19)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at YAMLSeq.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLSeq.js:76:27)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Object.addPairToJSMap (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/addPairToJSMap.js:32:34)
    at YAMLMap.toJSON (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/YAMLMap.js:124:28)
    at Object.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/nodes/toJS.js:22:26)
    at Document.toJS (/<path-to>/garden-io/garden/core/node_modules/yaml/dist/doc/Document.js:301:26)
    at prepareResource (/<path-to>/garden-io/garden/core/build/src/config/base.js:133:22)
    at /<path-to>/garden-io/garden/core/build/src/config/base.js:114:16
````
 
### What did you do?

Ran any Garden command.

### Your environment

* **OS:** macOS Monterey
* **Garden version:** Latest main

### Frequency

Always.

### Workaround

Write correct YAML (it's not as easy as it sounds) :)

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:
- chore(deps): update yaml to 2.3.2
- fix: prevent crash due to unresolved alias in yaml
- improvement: use loadAndValidateYaml for both kubernetes manifests and garden configs
- test: add tests for loadAndValidateYaml
- improvement: eliminate explicit any in loadAndValidateYaml

**Which issue(s) this PR fixes**:

Fixes #5186

**Special notes for your reviewer**:
This is a workaround for possible upstream bug described in https://github.com/eemeli/yaml/issues/497

Manual test looks like this:

```
% gdev deploy  
Deploy 🚀 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment local.default
Could not parse frontend.garden.yml in directory /Users/steffen/work/github/garden/examples/demo-project/frontend as valid YAML: YAMLException: unidentified alias "foobar" (2:14)

 1 | kind: Build
 2 | name: *foobar
------------------^
 3 | description: Frontend service container image
 4 | type: container
 ```

and for a kubernetes manifest:
```
% gdev deploy redis
Deploy 🚀

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment local.default
ℹ cloud-dashboard      → View command results at: https://app.garden.io/go/command/RWwxXGFhUl

ℹ providers            → Getting status...
✔ providers            → Cached (took 0.8 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0 sec)
ℹ deploy.redis         → missing
ℹ deploy.redis         → Deploying version v-96dc07041c...
✖ deploy.redis         → Failed (took 0 sec)
✖ deploy.redis         → Failed processing Deploy type=kubernetes name=redis (took 0.06 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not parse redis.yml in directory /Users/steffen/work/github/garden/examples/kubernetes-deploy/redis (specified in Deploy type=kubernetes name=redis) as valid YAML: YAMLException: unidentified alias "bar" (4:10)

 1 | ---
 2 | # Source: redis/templates/secret.yaml
 3 | apiVersion: v1
 4 | foo: *bar
--------------^
 5 | kind: Secret
 6 | metadata:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
1 deploy action(s) failed!

See .garden/error.log for detailed error message
```

### CODE REVIEW

File: core/src/plugins/kubernetes/kubernetes-type/common.ts [hunk 1]
```diff
@@ -464,10 +464,19 @@ function parseKubernetesManifests(str: string): KubernetesResource[] {
     }
   }
 
-  // TODO: We should use schema validation to make sure that apiVersion, kind and metadata are always defined as required by the type.
-  const manifests = docs.map((d) => d.toJS()) as KubernetesResource[]
+  let manifests: any[]
+  try {
+    manifests = docs.map((d) => d.toJS())
```
Comment (stefreak) [inline core/src/plugins/kubernetes/kubernetes-type/common.ts:469]: Maybe better if we call `loadAndValidateYaml` here as well, instead of duplicating the logic.

File: core/test/unit/src/config/base.ts [hunk 2]
```diff
@@ -591,3 +593,136 @@ describe("findProjectConfig", async () => {
     })
   })
 })
+
+describe("loadAndValidateYaml", () => {
```
Comment (eysi09) [inline core/test/unit/src/config/base.ts:597]: Great tests!

**Review by eysi09 — APPROVED** [review]
This looks good to me!

Thanks for adding the tests, great work!
