### PR TITLE
fix(template): establish backwards bug-compatibility for kubernetes manifest files

### LINKED ISSUE #6711: [Bug]: Templating logic change in garden 0.13.46 breaks deploys
### Current behavior

```
Error from server (Invalid): error when creating "STDIN": Ingress.networking.k8s.io "${this.name}-0" is invalid: [metadata.name: Invalid value: "${this.name}-0": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.rules[0].host: Invalid value: "${providers.kubernetes.outputs.default-hostname}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.rules[0].http.paths[0].backend.service.name: Invalid value: "${this.name}": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]
Error from server (Invalid): error when creating "STDIN": Ingress.networking.k8s.io "${this.name}-1" is invalid: [metadata.name: Invalid value: "${this.name}-1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.rules[0].host: Invalid value: "${providers.kubernetes.outputs.default-hostname}": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.rules[0].http.paths[0].backend.service.name: Invalid value: "${this.name}": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]
Error from server (Invalid): error when creating "STDIN": Service "${this.name}" is invalid: [metadata.name: Invalid value: "${this.name}": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'), spec.ports[0].targetPort: Invalid value: "${var.port}": must contain only alpha-numeric characters (a-z, 0-9), and hyphens (-), spec.selector: Invalid value: "${this.name}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

### Expected behavior

To work the way it has

### Reproducible example

Not entirely sure, so here's some snippets.
project.garden.yml:
```
variables:
  service: task
  deploy-extra-env-vars: []

environments:
  - name: dev
    defaultNamespace: user-${local.username}
    variables:
      buildversion: user-${local.username}
      default-hostname: ${var.service}-user-${local.username}.dev.mycompany.com
```
manifest:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${this.name}-0
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ${providers.kubernetes.outputs.default-hostname}
      http:
        paths:
          - pathType: Prefix
            path: "/v1"
            backend:
              service:
                name: ${this.name}
                port:
                  number: 80
```

### Workaround

Reverting to 0.13.45 works.

### Your environment

* **OS:** Ubuntu
* **How I'm running Kubernetes:** EKS

`garden version`
0.13.46

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:

Template strings in Kubernetes manifest files are partially resolved for legacy reasons. The partial resolve behaviour has been changed to improve sanity in https://github.com/garden-io/garden/pull/6685 but for kubernetes manifest files, we need to have a version of the old behaviour.

The expected legacy behaviour looks like this:
- If template strings reference variables that do not exist there is no error
- If a template string contains multiple template expressions, each expression can be partially resolved.
- Template expressions are evaluated before parsing yaml, which means that valid yaml with template expressions can be resolved to invalid yaml (e.g. if variable values contain special characters)

This legacy behaviour can lead to quite some surprises and UX problems, for example https://github.com/garden-io/garden/issues/5266

I would suggest that we remove this functionality in 0.14 in favor of the `patchManifests` feature

**Which issue(s) this PR fixes**:

Fixes #6711

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/util/fs.ts [hunk 1]
```diff
@@ -253,14 +253,14 @@ export async function makeTempDir({
 }: { git?: boolean; initialCommit?: boolean } = {}): Promise<TempDirectory> {
   const tmpDir = await tmp.dir({ unsafeCleanup: true })
   // Fully resolve path so that we don't get path mismatches in tests
-  const tmpPath = await realpath(tmpDir.path)
+  tmpDir.path = await realpath(tmpDir.path)
```
Comment (stefreak) [inline core/src/util/fs.ts:256]: This change was needed to make it possible to run the integ tests locally on macos.

**Review by vvagaytsev — APPROVED** [review]
Great job! 🚀

**Comment by thsig** [comment]
I very much agree that we should deprecate this in 0.14.

There are also problems in versioning `kubernetes` actions that use template strings in manifest files: If a variable is used in a manifest file but doesn't appear in the action config, changing that variable won't change the action version (since it's computed based on the unresolved manifest file).

**Comment by stefreak** [comment]
If we want to deprecate this, we need to deprecate this in 0.13 and remove it in 0.14. That way users can be sure that their configuration will work with 0.14 if they eliminate the deprecation warnings.

**Comment by stefreak** [comment]
Would be good to have an easy to use alternative, e.g. an `includeYaml` statement or a `templateFile` statement
