### PR TITLE
Fix log tailing issues

### LINKED ISSUE #411: Garden logs -t doesn't handle service restarts
### Current Behavior

When running `garden logs -t` and `garden dev` and you make a change to a service garden doesn't detect this and stops being able to follow the logs

There is also a Deprecation warning from moment?

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: rpc, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/app/garden-service/node_modules/moment/moment.js:320:98)
    at configFromString (/app/garden-service/node_modules/moment/moment.js:2368:15)
    at configFromInput (/app/garden-service/node_modules/moment/moment.js:2594:13)
    at prepareConfig (/app/garden-service/node_modules/moment/moment.js:2577:13)
    at createFromConfig (/app/garden-service/node_modules/moment/moment.js:2544:44)
    at createLocalOrUTC (/app/garden-service/node_modules/moment/moment.js:2631:16)
    at createLocal (/app/garden-service/node_modules/moment/moment.js:2635:16)
    at hooks (/app/garden-service/node_modules/moment/moment.js:12:29)
    at Stream.proc.stdout.pipe.on (/app/garden-service/build/plugins/kubernetes/actions.js:295:29)
    at Stream.emit (events.js:182:13)
    at drain (/app/garden-service/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/app/garden-service/node_modules/through/index.js:45:5)
    at emit (/app/garden-service/node_modules/split/index.js:37:14)
    at Stream.<anonymous> (/app/garden-service/node_modules/split/index.js:60:7)
    at _end (/app/garden-service/node_modules/through/index.js:65:9)
    at Stream.stream.end (/app/garden-service/node_modules/through/index.js:74:5)
    at Socket.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
result                    →                          → error: code = Unknown desc = Error: No such container: fb49980718a85976f30d95d21cc38b66efe344825a8cef48708a311a468967bc
vote                      →                          → error: code = Unknown desc = Error: No such container: c35073d998796767d1b351a1a0e965491e2a1e80239b3834ae0ae00319d8b6ea
db                        →                          → error: code = Unknown desc = Error: No such container: f561dc0e83bb93b8d281727e4ca40909f2c0295982b0095e63788098c769fb91
```

 ### Expected behavior

To be able to get the logs as things change (thats the point fo being able to view the logs with -t)

 ### Reproducible example

1. `garden deploy`
1. `garden logs -t` (keep runinng)
1. Edit a file to trigger a rebuild `echo " " > services/vote/templates/index.html`
1. `garden deploy`

 ### Suggested solution(s)

na.

 ### Additional context

Na 
 ### Your environment

Garden version: 0.8.0

### PR DESCRIPTION
**Pull request by edvald**
Closes #411 

Also adds support for log tailing for OpenFaaS functions.

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/logs.ts [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+  context: string
+  namespace: string
+  selector: string
+}
+
+export async function getServiceLogs(params: GetServiceLogsParams<ContainerModule>) {
+  const { ctx, service } = params
+  const context = ctx.provider.config.context
+  const namespace = await getAppNamespace(ctx, ctx.provider)
+  const selector = `service=${service.name}`
```
Comment (drubin) [inline garden-service/src/plugins/kubernetes/logs.ts]: Side note we should really come up with a better name here or annotate it with `io.garden.service` service is way too generic.  (obviously something we shouldn't do now)

Comment (edvald) [reply garden-service/src/plugins/kubernetes/logs.ts]: Yes I agree, noticed the same thing, just didn't want to lump that in here.

File: garden-service/src/plugins/kubernetes/logs.ts [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    .on("data", (line) => {
+      if (!line || line[0] !== "{") {
+        return
+      }
+      const obj = JSON.parse(line)
+      const [timestampStr, msg] = splitFirst(obj.message, " ")
+      try {
+        timestamp = moment(timestampStr).toDate()
+      } catch { }
+      void stream.write({ serviceName: service.name, timestamp, msg: msg.trimRight() })
```
Comment (drubin) [inline garden-service/src/plugins/kubernetes/logs.ts]: I understand why this  (`serviceName: service.name` instead of pod name) is here but its really a nice feature being able to easily see when the deployment happens is insanely useful.

Is it not possible to default to the pod name with coloured output?

Comment (drubin) [reply garden-service/src/plugins/kubernetes/logs.ts]: This also hides which container the logs come from with mutli pod containers (i.e sidecar).

Do we run a separate stern process for each service?

Comment (edvald) [reply garden-service/src/plugins/kubernetes/logs.ts]: The main point was to have a consistent structure across all providers. We could (and should) add an optional metadata field that the provider can populate, and possibly just prefix the log message with the coloured pod name in the K8s provider. But yea let's do it separately.

Comment (edvald) [reply garden-service/src/plugins/kubernetes/logs.ts]: Oh and yes, we do run a separate stern process per service, for the moment.

Please file an issue with feedback and suggestions, happy to improve this.
