### PR TITLE
fix(k8s): remove replicasets and daemonsets when deleting services

### LINKED ISSUE #379: Deleting a container service doesn't remove the replica sets
This seems to be a limitation of the Kubernetes API, see [this issue](https://github.com/kubernetes/kubernetes/issues/34052).

### PR DESCRIPTION
**Pull request by edvald**
Closes #379

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/deployment.ts [hunk 1]
```diff
@@ -528,7 +528,7 @@ export async function deleteContainerService(
     namespace,
     labelKey: "service",
     labelValue: serviceName,
-    objectTypes: ["deployment", "service", "ingress"],
+    objectTypes: ["deployment", "replicaset", "pod", "service", "ingress", "daemonset"],
```
Comment (drubin) [inline garden-service/src/plugins/kubernetes/deployment.ts]: Should we clean up the configmaps in the --meta namespace too?

Comment (edvald) [reply garden-service/src/plugins/kubernetes/deployment.ts]: Hmm, I think they should be disconnected usually. But we can revisit that later maybe.
