### PR TITLE
fix(vcs): .gitignore files were not respected

### LINKED ISSUE #1121: Garden isn't applying ignore files consistently
### Current Behavior

At various points, I've seen conflicting or confusing results on which files Garden moves to its build folder and/or syncs. To try and simplify this for the repo I'm working on, I ended up removing the `.gardenignore` file I had initially written, hoping to fall back on the documented `.gitignore` behavior:

> By default, patterns matched in .gitignore and .gardenignore files, found anywhere in the project, are ignored when scanning for modules and module sources.

When running Garden at high log levels to debug a different issue, I noticed that I was still getting resulted that diverged from the repo's `.gitignore` even though there was no more `.gardenignore` file or any ignore-related settings in the `garden.yml`.

To reduce the possibility space (such as the `.gardenignore` getting changed after files had already been copied), I deleted `.garden/build/qf` (the build I'm working on) and ran a fresh build command. It's not possible to either share the whole repo, or the entire gitignore, but I've added inline comments about what's broken for my repo.

gitignore section:
```
# mac garbage
.DS_Store
```

Incorrectly copied:
```
".DS_Store"
```

gitignore section:
```
config/development.yml
config/local.yml
config/local_prod.yml
```

Incorrect file:
```
"config/development.yml",
```

Gitignore section:
```
*.log
```

Incorrectly copied files:
```
"dtruss.log"
"error.log"
"output.log"
```

gitignore section:
```
tmp/*
!tmp/README.md
!tmp/capybara
tmp/capybara/*
!tmp/capybara/README.md
tmp/chrome/*
!tmp/chrome/README.md
```

Erroneously copied files:
```
,"tmp/.DS_Store","tmp/capybara/README.md","tmp/capybara/screenshot_2019-04-26-13-45-22.809.html","tmp/capybara/screenshot_2019-04-26-13-45-22.809.png","tmp/capybara/screenshot_2019-04-26-13-58-08.554.html","tmp/capybara/screenshot_2019-04-26-13-58-08.554.png","tmp/capybara/screenshot_2019-04-26-14-02-03.867.html","tmp/capybara/screenshot_2019-04-26-14-02-03.867.png","tmp/capybara/screenshot_2019-04-26-14-06-13.599.html","tmp/capybara/screenshot_2019-04-26-14-06-13.599.png","tmp/capybara/screenshot_2019-04-26-14-09-00.562.html","tmp/capybara/screenshot_2019-04-26-14-09-00.562.png","tmp/capybara/screenshot_2019-04-26-14-24-16.024.html","tmp/capybara/screenshot_2019-04-26-14-24-16.024.png","tmp/chrome/chrome.log","tmp/chrome/selenium.log","tmp/chrome/selenium.log.lck",
```

The Capybara _folder_ and its _README_ are not gitignored, but all the Capybara screenshots _are_. Garden isn't handling this case properly.

### Expected behavior

If there is no additional .gardenignore, then Garden gets the exact same results as the repo's gitignore file.

To clarify, all of the above cases are not files that were _generated_ in `.garden`, but files that were copied over to it despite being gitignored.

### Suggested solution(s)

Right now, you need to run at a high verbosity level to get copied file info, and it lives in a single logline as a list. To assist in debugging issues like this, there should be a `garden build-context` debugging command that outputs each file on their own line. I'd expect this to produce reports like:

- What is the merged set of ignores for this repo?
- Which files _would_ be copied into `.garden/build`?
- Which files are in `.garden/build` and _shouldn't_ be according to the ignores?

### Your environment

```
[eronarn@ip-192-168-10-243 qf]$ garden version && kubectl version && docker version
0.10.6
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### PR DESCRIPTION
**Pull request by edvald**
**What this PR does / why we need it**:

.gitignore files were not respected in the default configuration.

The issue also applied to other scenarios where users had multiple
dotIgnoreFiles set in their project configs.

**Which issue(s) this PR fixes**:

Fixes #1121

### CODE REVIEW

File: garden-service/test/unit/src/vcs/git.ts [hunk 1]
```diff
@@ -267,7 +267,30 @@ describe("GitHandler", () => {
...
+      const nameB = "boo.txt"
+      const pathA = resolve(tmpPath, nameA)
+      const pathB = resolve(tmpPath, nameB)
+      await createFile(pathA)
+      await createFile(pathB)
+
+      await addToIgnore(tmpPath, nameA)
+      await addToIgnore(tmpPath, nameB, ".testignore2")
+
+      await git("add", pathA)
```
Comment (eysi09) [inline garden-service/test/unit/src/vcs/git.ts]: Why do we add and commit the files? Shouldn't this also work for untracked files?
