### PR TITLE
fix(pulumi): propagate resolved action context to pulumi plugin commands

### LINKED ISSUE #5083: 0.13: [Bug]: Unable to parse modules key
### Current Behavior
When using `garden plugins pulumi preview` command, garden is unable to parse `${modules["${parent.name}-publish-image"].version}` 

`An error occurred while reading pulumi varfiles for action spring-boot-service: Unable to load varfile at '/home/workstation/thx/workspace/garden-sample-project/garden-sample-project/config/global.yaml': Error: Invalid template string (
### Expected behavior
garden should parse the `${modules["${parent.name}-publish-image"].version}` .

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:
This fixes the regressions introduced in `0.13`. In `0.12`, references to `${modules.*}` in the Pulumi varfiles were possible.
This PR fixes `0.13` to use:
* the `${actions.*}` references in Pulumi varfiles
* the `${modules.*}` references with module-based configs

**Which issue(s) this PR fixes**:

Fixes #5083

**Special notes for your reviewer**:

### CODE REVIEW

File: plugins/pulumi/src/commands.ts [hunk 1]
```diff
@@ -349,24 +367,27 @@ function makePulumiCommand({ name, commandDescription, beforeFn, runFn, afterFn
 
       beforeFn && (await beforeFn({ ctx, log }))
 
-      const provider = ctx.provider as PulumiProvider
-
+      const pulumiProvider = ctx.provider as PulumiProvider
       const actions = graph.getDeploys({ names }).filter((a) => a.type === "pulumi")
+      // Provider resolution is a heavy operation.
```
Comment (thsig) [inline plugins/pulumi/src/commands.ts:372]: Let's delete this comment—kf the providers have already been resolved on a `garden` instance, the resolved providers are cached.

**Review by thsig — APPROVED** [review]
Good stuff! Added one minor comment there.

File: plugins/pulumi/src/commands.ts (hunk 1 above)
Comment (vvagaytsev) [reply plugins/pulumi/src/commands.ts]: Removed in f8260abef234b9ee89917b428e842369c6234200.

**Review by thsig — APPROVED** [review]
