### PR TITLE
fix: login/logout using the configured domain

### LINKED ISSUE #4049: [BUG] Garden Login always resolves app.garden even if another domain is configured
When using `garden login` it will always try to login to https://app.garden. The correct behavior is to give precedence to the domain in the configuration or as env variable.

Introduced in https://github.com/garden-io/garden/commit/7f93b908

### PR DESCRIPTION
**Pull request by mkhq**
**What this PR does / why we need it**:

Ensures that the login/logout commands uses the cloud domain in the project config. Both have the `noProject` flag set which leads to the garden instance not being initialized with a project config. Ensures that this is compatible with `garden dev` and also includes login/logout in the help listing.

**Which issue(s) this PR fixes**:

Fixes #4049 

**Special notes for your reviewer**:

@edvald There was an earlier commit which reverted this behavior because of the dev command, https://github.com/garden-io/garden/commit/7f93b90830e1968526fa7f748e6f195c9a6e4421. Could you give some more context on how this relates?

### CODE REVIEW

File: core/src/commands/login.ts [hunk 1]
```diff
@@ -38,26 +39,24 @@ export class LoginCommand extends Command {
...
-          {
-            root: garden.projectRoot,
-          }
-        )
-      }
+    // NOTE: The Cloud API is missing from the Garden class for commands with noProject
+    // so we initialize it here. noProject also make sure that the project config is not
+    // initialized in the garden class, so we need to read it in here to get the cloud
+    // domain.
+    const projectConfig: ProjectResource | undefined = await cli!.getProjectConfig(log, garden.projectRoot)
```
Comment (edvald) [inline core/src/commands/login.ts:46]: There was a reason for changing this. The `cli` parameter is not populated when running from the dev command. This will need to be fixed differently, with that in mind.

**Review by edvald — CHANGES_REQUESTED** [review]

File: core/src/commands/login.ts (hunk 1 above)
Comment (mkhq) [reply core/src/commands/login.ts:46]: `login` and `logout` are currently not listed as commands in the `garden dev` help. Should we make that possible?

Comment (edvald) [reply core/src/commands/login.ts:46]: They should be listed imo. I think it's a reasonable thing to do in the console.

File: core/src/cli/command-line.ts [hunk 2]
```diff
@@ -50,6 +50,7 @@ const directInputKeys = [
 ]
 
 const hideCommands = ["config analytics-enabled", "tools"]
+const overrideHiddenCommands = ["login", "logout"]
```
Comment (edvald) [inline core/src/cli/command-line.ts:53]: A simpler approach would be to just remove the `hidden` flag from the commands :P I don't see any reason not to.

**Comment by edvald** [comment]
One last comment, otherwise seems good to me. Did you test it in the dev command?

File: core/src/cli/command-line.ts (hunk 2 above)
Comment (mkhq) [reply core/src/cli/command-line.ts:53]: Yeah, this is a bit clunky... I looked into where `hidden` is used and found this for the reference docs: https://github.com/garden-io/garden/blob/0.13/core/src/docs/commands.ts#L26.

**Comment by mkhq** [comment]
> One last comment, otherwise seems good to me. Did you test it in the dev command?

Yes a couple of times :)

File: core/src/cli/command-line.ts (hunk 2 above)
Comment (edvald) [reply core/src/cli/command-line.ts:53]: Oh I meant specifically for the login/logout commands. The flag is not necessary on them, and I'm not even sure why it's there in the first place.

**Comment by vvagaytsev** [comment]
@edvald is this ready to go?

**Review by edvald — APPROVED** [review]
