### PR TITLE
fix(cli): exit code 1 on unknown commands, sub-commands and flags

### LINKED ISSUE #4911: [Bug] Garden exists with `0` exit code on unsupported options and sub-commands
### Current Behavior

**Case 1.**
When `garden` is executed with an unrecognized _option_ and without any command (e.g. `garden --bad`) it prints the usage help and exists with code `0`.

**Case 2.**
When `garden` is executed with an unrecognized _sub-command_ (e.g. `garden run bad`) it prints the usage help and exists with code `0`.

### Expected behavior

In both cases above `garden` should exit with code `1` if an unrecognized option or sub-command is passed.

### Reproducible example

Run these commands:

```console
# Unrecognized option:
> garden --bad
# usage output omitted
# ...
> echo $?
0   # <- this is wrong

# Unrecognized sub-command:
> garden delete bad
# usage output omitted
# ...
> echo $?
0   # <- this is wrong
```

### Workaround

No

### Suggested solution(s)

Implement checks for `garden`'s options inspection and exit with code `1` on unrecognized options.

**Note!** The old behaviour for other testing scenarios is correct and must be kept:

```console
# Unrecognized (invalid) command:
> garden bad
# usage output omitted
# ...
> echo $?
1

# Unrecognized (invalid) _command_ option:
> garden deploy --bad
# usage output omitted
# ...
> echo $?
1

# Recognized (valid) option:
> garden --help
# usage output omitted
# ...
> echo $?
0
```

**Make sure we have the tests for the scenarios above. Please implement the missing test scenarios if any.**

### Additional context

This comes from the discussion started in #4868.

### Your environment

* **OS:** all
* **How I'm running Kubernetes:** does not matter

`garden version 0.13.9`
`garden version 0.12.63`

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:
This PR brings strict consistency into Garden command exit codes and fixes the possible CI problems like the ones we got in #4868.

**Which issue(s) this PR fixes**:

Fixes #4911

**Special notes for your reviewer**:
This PR has been done in TDD mode :)
The test specs were written first.

~To be back-ported to `0.12`.~

TODOs (to be addressed in a separate PR):
* ensure the error message is always printed on unrecognized flag
* ensure the error message is always printed on unrecognized command or sub-command

### CODE REVIEW

File: core/src/cli/cli.ts [hunk 1]
```diff
@@ -493,21 +498,54 @@ ${renderCommands(commands)}
...
+
       return done(0, command.renderHelp())
     }
 
+    // Handle incomplete subcommand listings.
+    // A complete sub-command won't be recognized as CommandGroup
+    if (command instanceof CommandGroup) {
+      const subCommandName = rest[0]
+      if (subCommandName === undefined) {
+        // exit code 0 if sub-command is not specific and --help flag is passed, e.g. garden get --help
```
Comment (stefreak) [inline core/src/cli/cli.ts:532]: this comment seems wrong/ out of date, as the line below it exits with code 1

**Review by stefreak — DISMISSED** [review]
Great work! I have one minor comment on a comment. 

I like the tests a lot ❤️

**Comment by stefreak** [comment]
One comment on the plan to backport this to 0.12: Do we have to do that? I think it might not be important enough to justify the effort (But I might be wrong, you might have good reasons).

File: core/src/cli/cli.ts (hunk 1 above)
Comment (vvagaytsev) [reply core/src/cli/cli.ts]: Good catch, thanks! I fixed that in e474f896582f3b337c318fff1aa2515a9d193e51,

**Comment by vvagaytsev** [comment]
> One comment on the plan to backport this to 0.12: Do we have to do that? I think it might not be important enough to justify the effort (But I might be wrong, you might have good reasons).

It's not super critical, but it might be better to align the exit code behavior between 0.12 and 0.13. The back-port should be a big effort. We're going to do the next `0.12` release soon, so we can include this fix too.

**Review by stefreak — APPROVED** [review]
