### PR TITLE
fix(k8s): fix IO handling for exec command

### LINKED ISSUE #2064: The exec command doesn't work with the K8s provider
### Current Behavior

Garden appears to hang when running something like `garden exec api /bin/sh`. The reasons is that the output from the pod that's being attached to is never rendered in the users terminal.

More precisely, the `message` events for the websocket connection here are not handled:

https://github.com/garden-io/garden/blob/master/core/src/plugins/kubernetes/api.ts#L600

It's not clear to me whether the K8s library should be doing that or whether it needs to be handled explicitly. 

### Expected behavior

Output should be visible.

### Reproducible example

Run `garden exec backend /bin/sh --env remote` in the `demo-project`. 

### Workaround

Use `kubectl` directly, for example:

```
kubectl exec <pod-name> -n <namespace-name> -it -- /bin/sh
``` 

### Your environment

Lastest `master`.

### PR DESCRIPTION
**Pull request by thsig**
**What this PR does / why we need it**:

This fixes a regression that was introduced when we started using the k8s API to run commands in pods.

**Which issue(s) this PR fixes**:

Fixes #2064.

### CODE REVIEW

**Comment by eysi09** [comment]
Might be useful to add a sanity check for this in the `test-release.sh` script.

File: core/src/plugins/kubernetes/api.ts [hunk 1]
```diff
@@ -574,9 +575,29 @@ export class KubeApi {
...
+      }
+      if (stdin) {
+        /**
+         * We use raw mode for stdin to ensure that control characters aren't intercepted by the terminal and that
+         * input isn't echoed back (among other things).
+         *
+         * See https://nodejs.org/api/tty.html#tty_readstream_setrawmode_mode for more.
+         */
+        const ttyStdin = stdin as ReadStream
+        ttyStdin.setRawMode(true)
```
Comment (edvald) [inline core/src/plugins/kubernetes/api.ts:594]: This can fail if something other than a TTY is passed in. I'd instead check for the `setRawMode` attribute, and set it if available (like in the `spawn()` utility function).

**Review by edvald — CHANGES_REQUESTED** [review]

File: core/src/plugins/kubernetes/api.ts (hunk 1 above)
Comment (thsig) [reply core/src/plugins/kubernetes/api.ts:594]: Aha, good point.

Comment (thsig) [reply core/src/plugins/kubernetes/api.ts]: Updated. Or did you also want the `rawMode` parameter added here (and, by extension, to `ExecOpts`)?

Comment (edvald) [reply core/src/plugins/kubernetes/api.ts]: No this looks good 👍

**Review by edvald — APPROVED** [review]

**Review by eysi09 — CHANGES_REQUESTED** [review]
I would really like to see a simple test for this. It’s core functionality that broke without warning and we didn’t notice for weeks.

**Comment by thsig** [comment]
I'm adding a test case for this to the pre-release tests, for what it's worth. Testing the interactive shell functionality from a separate process might be a bit tricky (or so I thought).

**Comment by eysi09** [comment]
> I'm adding a test case for this to the pre-release tests, for what it's worth.

Yes that's exactly what I had in mind, as per my comment above. Just requested a change because this had already been approved.

**Comment by thsig** [comment]
Ok, I've added a "test case" for the exec command to `scripts/test-release.sh`.

**Review by edvald — APPROVED** [review]
