### PR TITLE
fix(core): remove StageBuildTask from GetServiceStatusTask dependencies

### LINKED ISSUE #1583: Helm modules deletes the build folder when trying to access logs through the dashboard.
### Current Behavior

From Slack user Yann Irbah:

> :wave: Hi there. I (finally) started to add Garden to one of our new projects and I have a weird behavior. Everything was working fine with simple container modules. Then I started using Helm modules and every time I try to access logs through the UI, it deletes the `build` folder for the modules in the `.garden` directory and start looping with the following error `.garden/build/blueprints-chart/garden-values.yml: no such file or directory` (which makes sense since the directory is empty at this point).

Link to [discussion](https://kubernetes.slack.com/archives/CKM7CP8P9/p1581085718213500).

### PR DESCRIPTION
**Pull request by eysi09**
**What this PR does / why we need it**:

We shouldn't be staging the build when getting the service status as it
can remove build artifacts like those generated by the `helm` module. Had
to make adjustments to the `kubernetes` module `getServiceStatus` handler to
account for this change.

**Which issue(s) this PR fixes**:

Fixes #1583

### CODE REVIEW

File: garden-service/src/plugins/kubernetes/kubernetes-module/common.ts [hunk 1]
```diff
@@ -50,11 +57,21 @@ export async function getManifests(
...
 /**
  * Read the manifests from the module config, as well as any referenced files in the config.
+ *
+ * @param module The kubernetes module to read manifests for.
+ * @param readFromSrcDir Whether or not to read the manifests from the module build dir or from the module source dir.
+ * In general we want to read from the build dir to ensure that manifests added via the `build.dependencies[].copy`
+ * field will be included. However, in some cases, e.g. when getting the service status, we can't be certain that
+ * the build has been staged and we therefore read the manifests from the source.
+ *
+ * FIXME: Always read from build dir.
```
Comment (edvald) [inline garden-service/src/plugins/kubernetes/kubernetes-module/common.ts]: The fix for this will rather be to check a version hash, when possible, not to always read from the build dir.

Comment (edvald) [reply garden-service/src/plugins/kubernetes/kubernetes-module/common.ts]: I don't expect we'll ever revert to building/staging before getting service statuses

File: garden-service/src/types/plugin/service/getServiceStatus.ts [hunk 2]
```diff
@@ -27,6 +27,9 @@ export const getServiceStatus = {
 
     Called ahead of any actions that expect a service to be running, as well as the
     \`garden get status\` command.
+
+    NOTE: This handler should not use the build directory since it's not guaranteed
+    that the build will be staged.
```
Comment (edvald) [inline garden-service/src/types/plugin/service/getServiceStatus.ts]: "... staged or completed before this handler is called."

File: garden-service/src/plugins/kubernetes/kubernetes-module/common.ts (hunk 1 above)
Comment (eysi09) [reply garden-service/src/plugins/kubernetes/kubernetes-module/common.ts]: And in that case, we won't need the manifests in the `getServiceStatus` handler, right?

Comment (edvald) [reply garden-service/src/plugins/kubernetes/kubernetes-module/common.ts]: Fair point. Depends if we only check the hash, or do both. In any case, all good, we'll revisit at that time.
