### PR TITLE
chore: fix TOC when no README is present

### LINKED ISSUE #1180: Table of contents generator: Handle dirs with no READMEs
The table of contents generator currently assumes that all directories have a `README.md` file which won't always be the case. We should fix this. See this PR for details: #1179 for more details.

### PR DESCRIPTION
**Pull request by ellenkorbes**
**What this PR does / why we need it**:

Now when there's no `README.md` inside a subdirectory the link for that directory in the table of contents will:
- Be title cased
- Point to the first file in the directory (before custom/metadata sorting is applied)

**Which issue(s) this PR fixes**:

Fixes #1180

**Special notes for your reviewer**:

### CODE REVIEW

File: garden-service/src/docs/table-of-contents.ts [hunk 1]
```diff
@@ -55,6 +56,17 @@ function attachMetadata(tree: FileTree) {
     if (e.code !== "ENOENT") {
       throw (e)
     }
+    if (e.code === "ENOENT" && tree.type === "directory") {
+      let checkFile: string | undefined
+      try {
+        checkFile = readFileSync(tree.children[0].path, "utf-8")
```
Comment (edvald) [inline garden-service/src/docs/table-of-contents.ts]: Using `pathExists()` here would be much cleaner.

File: garden-service/package.json [hunk 2]
```diff
@@ -103,6 +103,7 @@
     "sywac": "^1.2.2",
     "tar": "^4.4.10",
     "terminal-link": "^2.0.0",
+    "title-case": "^2.1.1",
```
Comment (eysi09) [inline garden-service/package.json]: We actually also have `humanize` and `titleize` (imported below) and `titleize(humanize(string))` is basically the same as `titleCase(string)`. I suggest we either remove the `title-case` library and add a `titleCase` util function in `util/string` that uses `titleize` and `humanize`. Or alternatively, remove `titleize` and `humanize` and just use `title-case`.

File: garden-service/src/docs/table-of-contents.ts (hunk 1 above)
Comment (ellenkorbes) [reply garden-service/src/docs/table-of-contents.ts]: Turns out that checking is not necessary since dtree does that for me already elsewhere in the code.

File: garden-service/src/docs/table-of-contents.ts [hunk 3]
```diff
@@ -46,14 +49,21 @@ function createNewTree(tree: FileTree, transform: Function): FileTree {
 
 function attachMetadata(tree: FileTree) {
   if (tree.type === "directory") {
-    tree.path = tree.path + "/README.md"
+    if (tree.children.length > 0) {
+      tree.path = tree.path + "/README.md"
```
Comment (edvald) [inline garden-service/src/docs/table-of-contents.ts]: Better to use `resolve(tree.path, "README.md")`, otherwise it won't work cross platform.

**Comment by ellenkorbes** [comment]
@edvald @eysi09 Please review again.

File: garden-service/src/docs/table-of-contents.ts [hunk 4]
```diff
@@ -117,6 +141,10 @@ const indent: string = "  "
 
 export function generateTableOfContents(docsRoot: string): string {
   const rawTree = <FileTree>dtree(docsRoot, { extensions: /\.md/ })
+  if (rawTree === null) {
+    throw ("Directory not found.")
```
Comment (eysi09) [inline garden-service/src/docs/table-of-contents.ts]: This should be `throw new Error("...")`

Comment (eysi09) [inline garden-service/src/docs/table-of-contents.ts]: This should be `throw new Error("...")`

Comment (ellenkorbes) [reply garden-service/src/docs/table-of-contents.ts]: @eysi09 Done, please merge :-)

**Comment by ellenkorbes** [comment]
@eysi09 Done, please merge :-)
