### PR TITLE
fix: fix source builds processing in build-staging + updated `build-dependencies` example

### LINKED ISSUE #3754: 0.13 example update: build-dependencies

### PR DESCRIPTION
**Pull request by vvagaytsev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3754

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by vvagaytsev** [comment]
Converting back to draft. The deployment command fails with `-dev` flag.

File: core/src/plugins/container/config.ts [hunk 1]
```diff
@@ -233,8 +233,6 @@ const devModeSyncSchema = () =>
   joi.object().keys({
     source: joi
       .posixPath()
-      .relativeOnly()
-      .subPathOnly()
```
Comment (Walther) [inline core/src/plugins/container/config.ts:237]: does this removal have possible side effects?

i'm reminded of https://github.com/garden-io/garden/pull/3445 and https://github.com/garden-io/garden/issues/3487

Comment (vvagaytsev) [reply core/src/plugins/container/config.ts:238]: We don't have these limitations in `0.12`, so I just aligned the validation logic with the `main` branch. @edvald do we want to allow using of the absolute paths as sync sources?

File: core/src/build-staging/build-staging.ts [hunk 2]
```diff
@@ -99,8 +98,11 @@ export class BuildStaging {
         })
       }
 
+      // init .garden/build directory of the source build before syncing it to the build directory of the target action
+      await this.syncFromSrc(sourceBuild, log)
```
Comment (vvagaytsev) [inline core/src/build-staging/build-staging.ts:102]: This can be avoided if we use `sourceRoot: sourceBuild.basePath(),` in [L105](https://github.com/garden-io/garden/pull/3758/files#diff-9eb4fcb064a98747d3c16f0bc8cb1301149611484b153f332b563716f33402e3R105).

But, if I got it correctly, all build actions' content should be copied to the `build` directory in `.garden/build/{action-name}`.

**Comment by vvagaytsev** [comment]
There are some test failures, moving it back to the draft state.

File: core/src/build-staging/build-staging.ts (hunk 2 above)
Comment (edvald) [reply core/src/build-staging/build-staging.ts:102]: Could be right but I'd like to look more closely at this.

File: core/src/plugins/container/config.ts (hunk 1 above)
Comment (edvald) [reply core/src/plugins/container/config.ts:238]: Yes, this is okay since these paths don't have bearing on builds or versioning. In fact, this doesn't even have to be a POSIX path, can just be any file path and should work with absolute paths on Windows as well.

File: core/src/build-staging/build-staging.ts (hunk 2 above)
Comment (vvagaytsev) [reply core/src/build-staging/build-staging.ts:102]: Thanks! It would be nice if you could take a look! By the way, this might cause some [test failures](https://app.circleci.com/pipelines/github/garden-io/garden/15406/workflows/fae39d2c-adf6-419d-8b8f-4f6ca4a19e08/jobs/257392), but I'm not sure. I wasn't able to reproduce the same failures locally.

Comment (vvagaytsev) [reply core/src/build-staging/build-staging.ts:102]: I reproduce the failures locally. Now, the test fails because `action.getFullVersion().files` in [L62](https://github.com/garden-io/garden/pull/3758/files#diff-9eb4fcb064a98747d3c16f0bc8cb1301149611484b153f332b563716f33402e3R62) does not contain the `a.txt` file which is produced by `module-a` Build action.

Still figuring out why that happens. Any help is highly appreciated :)

File: core/src/plugins/container/config.ts (hunk 1 above)
Comment (vvagaytsev) [reply core/src/plugins/container/config.ts:238]: Allowed Windows paths in https://github.com/garden-io/garden/pull/3758/commits/82de6d9d8a9a2ab8a21380238b21e179916931ae

File: core/src/build-staging/build-staging.ts [hunk 3]
```diff
@@ -51,7 +51,7 @@ export class BuildStaging {
     this.createdPaths = new Set()
   }
 
-  async syncFromSrc(action: BuildAction, log: Log) {
+  async syncFromSrc(action: BuildAction, log: Log, withDelete: boolean = true) {
```
Comment (Orzelius) [inline core/src/build-staging/build-staging.ts:54]: FYI ts will infer the type from assignment so technically `:boolean` is not needed here

Comment (Orzelius) [reply core/src/build-staging/build-staging.ts:54]: But I think adding boolean parameters like this is a bit ugly as it's hard to understand what they're supposed to be by just looking at the function call. Maybe convert to a destructured object instead? Your ide will probably have the option to help out with this.

**Comment by Orzelius** [comment]
Added a small non-blocking comment

File: core/src/build-staging/build-staging.ts (hunk 3 above)
Comment (vvagaytsev) [reply core/src/build-staging/build-staging.ts:54]: Agree, better to use parameter-object here. I'll refactor this in a separate commit.

Comment (vvagaytsev) [reply core/src/build-staging/build-staging.ts]: Refactored this in https://github.com/garden-io/garden/pull/3758/commits/d9f9fc1f820bf2c24979a0282c3994171d0d2f15

**Comment by vvagaytsev** [comment]
@edvald this is ready for review, could you take a look, please?

**Comment by Orzelius** [comment]
Will have a look first thing tomorrow

File: examples/build-dependencies/frontend/garden.yml [hunk 4]
```diff
@@ -1,44 +1,60 @@
...
-    ingresses:
-      - path: /hello-frontend
-        port: http
-      - path: /call-backend
-        port: http
-    dependencies:
-      - backend
-tests:
-  - name: unit
-    args: [npm, test]
```
Comment (Walther) [inline examples/build-dependencies/frontend/garden.yml:40]: looks like the unit test got dropped, let's add it back as another Test section

File: examples/build-dependencies/backend/garden.yml [hunk 5]
```diff
@@ -1,23 +1,41 @@
...
+
+---
+
+kind: Run
+name: backend
+description: Simple run task
+type: container
+
+spec:
+  command: [ "sh", "-c", "echo task output" ]
```
Comment (Walther) [inline examples/build-dependencies/backend/garden.yml:41]: idly pondering if we should keep these kinds of empty tasks and tests that only run `echo` or just remove them

**Review by Walther — APPROVED** [review]
two small comments, otherwise looks good to me! 🎉

**Review by Orzelius — APPROVED** [review]

File: examples/build-dependencies/frontend/garden.yml (hunk 4 above)
Comment (vvagaytsev) [reply examples/build-dependencies/frontend/garden.yml:40]: Good catch, thanks!

File: examples/build-dependencies/backend/garden.yml (hunk 5 above)
Comment (vvagaytsev) [reply examples/build-dependencies/backend/garden.yml:41]: Yep, maybe we can drop them. But, otoh each that config just demonstrates what Garden can do. So maybe it's fine to keep it :)
