### PR TITLE
fix(cli): enforce single character option aliases

### LINKED ISSUE #151: garden cli fails when using -log global option but not when using --loglevel
When running garden with the `-log` option, garden fails with the below error, but it works when using `--loglevel`

```
node ~/devel/node/garden/dist/src/bin/garden.js status -log verbose

USAGE

  garden status [options]

Global options
  -h, --help        Show help
                    [boolean]
....

  -log, --loglevel  Set logger level.
                    [enum] [default: info] [error, warn, info, verbose, debug, silly]


  -o, --output      Output command result in specified format (note: disables progress
                    logging).
                    [enum] [json, yaml]

Value "" is invalid for argument o or output. Choices are: json, yaml
```

### PR DESCRIPTION
**Pull request by eysi09**
Fixes #151

### CODE REVIEW

File: src/cli/cli.ts [hunk 1]
```diff
@@ -300,6 +300,11 @@ export class GardenCli {
 }
 
 export async function run(): Promise<void> {
-  const cli = new GardenCli()
-  return cli.parse().then(result => shutdown(result.code))
+  try {
+    const cli = new GardenCli()
+    return cli.parse().then(result => shutdown(result.code))
```
Comment (edvald) [inline src/cli/cli.ts]: I think it'd make sense to change this line along the way to
```
const result = await cli.parse()
shutdown(result.code)
```

Comment (eysi09) [reply src/cli/cli.ts]: Good catch! I threw in a finally statement there as well.
