### PR TITLE
fix: allow dashes in kaniko options

### LINKED ISSUE #5689: Kaniko extraFlags don't seem to work for --cache-repo
### Current Behavior

Trying to test various Kaniko configurations with AWS ECR so setting the `--cache-repo` parameter in `extraArgs` in `project.garden.yml`.

```
    buildMode: kaniko
    kaniko:
      extraFlags: ["--cache-repo", "${var.aws-account}.dkr.ecr.us-west-2.amazonaws.com/${var.service}"]
``` 
This fails due to a regex rejecting the second parameter.

> Invalid format for a kaniko flag. Expected it to match `/--([a-zA-Z]*)/`, actually got: `accountnumber.dkr.ecr.us-west-2.amazonaws.com/myproject`

So I tried setting it as a single string to bypass the regex:
```
    buildMode: kaniko
    kaniko:
      extraFlags: ["--cache-repo ${var.aws-account}.dkr.ecr.us-west-2.amazonaws.com/${var.service}"]
``` 
And get this:

> build.task-py             → [verbose] Starting Pod kaniko-myservice-0f8ae4 with command 'sh -c /kaniko/executor "--context" "dir:///.garden/context" "--dockerfile" "Dockerfile" "--destination" "accountnumber.dkr.ecr.us-west-2.amazonaws.com/myproject/myservice:v-4e23f7add0" "--cache-repo accountnumber.dkr.ecr.us-west-2.amazonaws.com/myproject" "--build-arg" "GARDEN_MODULE_VERSION=v-4e23f7add0" "--build-arg" "GARDEN_ACTION_VERSION=v-4e23f7add0" "--build-arg" "RUN_ENV=dev" "--target" "prod";
Error: unknown command "GARDEN_MODULE_VERSION=v-4e23f7add0" for "executor"
Run 'executor --help' for usage.

It appears the `--cache-repo` parameter needs to be a separate string but the [garden regex](https://github.com/garden-io/garden/blob/544318a61e0d72edbd29cedac6c9d6274ce5a96a/core/src/plugins/kubernetes/container/build/kaniko.ts#L211) won't allow it. 

### Expected behavior

To be able to supply a cache-repo to kaniko per garden documentation.

### Reproducible example

Info above.

### Workaround

Don't know of any workaround, the same regex is run if I try to put the extraFlags in the container spec.

### Suggested solution(s)

Improve or remove regex.

### Additional context

cluster-buildkit doesn't check formatting of `extraFlags` from the spec, not sure why kaniko does? I tested both 0.13 and 0.12 versions, wondering if this ever worked, doesn't look like that code has changed in over 3 years.

### Your environment
Ubuntu Linux 22.04
EKS
garden 0.12.67 and 0.13.24

### PR DESCRIPTION
**Pull request by stefreak**
Fixes #5689

### CODE REVIEW

File: core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts [hunk 1]
```diff
@@ -228,6 +228,10 @@ describe("kaniko build", () => {
       expect(getKanikoFlags(["--myToggle"])).to.deep.equal(["--myToggle", "--cache=true"])
     })
 
+    it("should allow options with dashes", () => {
+      expect(getKanikoFlags(["--my-toggle", "--my-name=banana"])).to.deep.equal(["--my-toggle", "my-name=banana", "--cache=true"])
```
Comment (stefreak) [inline core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts:232]:
```suggestion
      expect(getKanikoFlags(["--my-toggle", "--my-name=banana"])).to.deep.equal(["--my-toggle", "--my-name=banana", "--cache=true"])
```

**Review by vvagaytsev — APPROVED** [review]

**Review by vvagaytsev — APPROVED** [review]
