### PR TITLE
fix(k8s): use mode=inline for buildkit in-cluster builder as default

### LINKED ISSUE #3279: failed to solve: error writing manifest blob: failed commit on Garden v0.12.45
### Current Behavior

When running `garden deploy --env=dev`, the deploy fails trying to commit:
```
#20 exporting cache
#20 preparing build cache for export done
#20 writing layer sha256:109c04bbea473dcd39bfc58fe8612c1db408f94e9aaf614e32f703efa258ee42 0.1s done
#20 writing layer sha256:4d990e80d602f070b3258e9062eeda704e6cba7d1b38718a5e9ece2e82b4ed67
#20 writing layer sha256:4d990e80d602f070b3258e9062eeda704e6cba7d1b38718a5e9ece2e82b4ed67 0.1s done
#20 writing layer sha256:530afca65e2ea04227630ae746e0c85b2bd1a179379cbf2b6501b49c4cab2ccc
#20 writing layer sha256:530afca65e2ea04227630ae746e0c85b2bd1a179379cbf2b6501b49c4cab2ccc 0.1s done
#20 writing layer sha256:5b4b56e6b99464c54d3f129e00bd20b617c458db956feb2970245abc431fe85f
#20 writing layer sha256:5b4b56e6b99464c54d3f129e00bd20b617c458db956feb2970245abc431fe85f 0.1s done
#20 writing layer sha256:5cd4df23d1df20205bb8b136bfad8be74ae68a81ba829994bfa6735d23675441 0.1s done
#20 writing layer sha256:7685f6245a25ce74c09455867bb2d273d515a64df78a633837809dcca004c85b
#20 writing layer sha256:7685f6245a25ce74c09455867bb2d273d515a64df78a633837809dcca004c85b 0.1s done
#20 writing layer sha256:8162171ecb65551f90de8eb79be7a98850c0b4fa7af6e31150ad932d3ea3fb32
#20 writing layer sha256:8162171ecb65551f90de8eb79be7a98850c0b4fa7af6e31150ad932d3ea3fb32 0.1s done
#20 writing layer sha256:c49fb0f1c5aafb11b2258d5015e910ea395233e3f7347ec14e182db93fdfd493
#20 writing layer sha256:c49fb0f1c5aafb11b2258d5015e910ea395233e3f7347ec14e182db93fdfd493 0.1s done
#20 writing layer sha256:d450d4da0343091dd049727bcf8ccaae8c22b9b11cbb26823c403343ca9faa1c
#20 writing layer sha256:d450d4da0343091dd049727bcf8ccaae8c22b9b11cbb26823c403343ca9faa1c 0.1s done
#20 writing layer sha256:ff63b82a42d3d44071011eb2a1262a77c15520b940511c05ebd7a7c3019fdff6
#20 writing layer sha256:ff63b82a42d3d44071011eb2a1262a77c15520b940511c05ebd7a7c3019fdff6 0.1s done
#20 writing config sha256:0f835856accabfaef0764d02e067f1164f40e750aa14308d780424bcd74f24d6
#20 writing config sha256:0f835856accabfaef0764d02e067f1164f40e750aa14308d780424bcd74f24d6 0.9s done
#20 writing manifest sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c
#20 writing manifest sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c 0.7s done
#20 ERROR: error writing manifest blob: failed commit on ref "sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c": unexpected status: 404
 Not Found
------
 > importing cache manifest from registry.com/some-repository/conversations:_buildcache:
------
------
 > exporting cache:
------
error: failed to solve: error writing manifest blob: failed commit on ref "sha256:4ccee87270cf301e5c8d8cda34ff1c34493d9aeb599dd4fb30f7e70591260c0c":
unexpected status: 404 Not Found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy action(s) failed!
```

It seems the default behavior in v0.12.45, sets
```
clusterBuildkit:
  cache:
    - type: registry
      mode: max
```
however, in our version of harbor, this isn't yet supported as outlined in this https://github.com/goharbor/harbor/issues/14774

### Expected behavior

I expect the deploy to go through without any errors.

### Reproducible example

garden version: v0.12.45
harbor version: v2.5.3-797c3536
kubernetes(eks) version: v1.21.14-eks-18ef993

command: `garden deploy --env=dev`

### Workaround

Downgrade to v0.12.44.
or run `garden deploy --env=dev` twice.

or on v0.12.45, specify:
```
clusterBuildkit:
  cache:
    - type: registry
      mode: inline
```

### Suggested solution(s)

we could default the mode to `inline`, rather than `max`.

### Additional context

tried clearing local garden directory, cleared running garden pods, reproduced failing environment on engineers machine on v0.12.45, and working environment on v0.12.44.

The only resolution found (without rerunning commands) was to downgrade garden from v0.12.45 to v0.12.44

### Your environment

macOS: Monterey v12.5.1
harbor version: v2.5.3-797c3536
kubernetes(eks) version: v1.21.14-eks-18ef993
garden version: v0.12.45

edit: add more context to what went wrong, linked an issue, and suggested a possible solution.

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:

While most self-hosted registries do support buildkits mode=max,
harbor doesnt and so we can't use mode=max as a default unless we find
a way to autodetect the support for an unknown registry.

**Which issue(s) this PR fixes**:

Fixes #3279

**Special notes for your reviewer**:

### CODE REVIEW

File: core/src/plugins/kubernetes/container/build/buildkit.ts [hunk 1]
```diff
@@ -322,18 +322,29 @@ export const getSupportedCacheMode = (
...
 
-  // Detect AWS ECR
-  if (deploymentImageName.includes(".dkr.ecr.")) {
-    return "inline"
-  }
+  // NOTE: If you change this, please make sure to also change the table in our documentation in config.ts
+  const allowList = [
+    /^([^/]+\.)?pkg\.dev\//i, // Google Package Registry
+    /^([^/]+\.)?azurecr\.io\//i, // Azure Container registry
+    /^hub.docker.com\//i, // DockerHub
```
Comment (stefreak) [inline core/src/plugins/kubernetes/container/build/buildkit.ts:329]:
```suggestion
    /^hub\.docker\.com\//i, // DockerHub
```

File: core/src/plugins/kubernetes/container/build/buildkit.ts [hunk 2]
```diff
@@ -322,18 +322,29 @@ export const getSupportedCacheMode = (
...
+    /^ghcr.io\//i, // GitHub Container registry
```
Comment (stefreak) [inline core/src/plugins/kubernetes/container/build/buildkit.ts:330]:
```suggestion
    /^ghcr\.io\//i, // GitHub Container registry
```

File: core/src/plugins/kubernetes/container/build/buildkit.ts [hunk 3]
```diff
@@ -322,18 +322,29 @@ export const getSupportedCacheMode = (
...
+    inClusterRegistryHostname, // Garden in-cluster registry
```
Comment (TimBeyer) [inline core/src/plugins/kubernetes/container/build/buildkit.ts:331]: What do you think about turning this into 
```
new RegExp(`^${inClusterRegistryHostname}/`, 'i')
```
so that we don't have to have the `if/else` construct and always rely on RegExp here?

Comment (stefreak) [reply core/src/plugins/kubernetes/container/build/buildkit.ts:331]: Yes we could do that, but I didn't feel good about passing a string into the RegExp constructor as it could contain special characters in the future

But you know what, it's pretty unlikely so Ill do that

**Review by TimBeyer — APPROVED** [review]
