### PR TITLE
fix(kubernetes): detect that pod has been killed

### LINKED ISSUE #3535: Bug: Tests sometimes reported as successful when the Pod has been deleted (e.g. due to eviction)
## Bug

On some Kubernetes cluster, tests are reported as successful when the Pod has been deleted (e.g. due to eviction).

### Reproducible example
1. Modify `example/demo-project/frontend/test/integ.js` like so:
```
describe('GET /call-backend', async () => {
+  let foo = 0
+  while (true) {
+    await new Promise(resolve => setTimeout(resolve, 1000))
+    foo += 1
+    console.log(`Foo ${foo}`)
+  }
```

This helps reproduce the issue by causing the tests to never complete, but continuously log "Foo" every second.

2. Modify `example/demo-project/garden.yml` to use a remote Kubernetes cluster namespace. (E.g. garden-ci or demo-3)

2. Run `% gdev test frontend -n integ -f --remote`

3. While the integ test is running, interrupt it by deleting the pod:

```
% kubectl get po|grep integ|awk '{print $1}'|xargs kubectl delete pod
pod "test-frontend-integ-8b976b" deleted
```

Another way to kill the running pod that is more likely in the real world is e.g. draining the node.

### Expected behavior

I expect a clear and actionable error message in this case.

```
Failed running integ tests in module frontend. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Could not find Pod test-frontend-integ-a197a5 – it might have been deleted or evicted.

Please read this FAQ for hints how to prevent Pods from being evicted mid-run: garden.io/xyz

Latest Pod events:

LAST SEEN   TYPE     REASON      OBJECT                           MESSAGE
10m         Normal   Scheduled   pod/test-frontend-integ-559e1a   Successfully assigned demo-project-default/test-frontend-integ-559e1a to docker-desktop
10m         Normal   Pulled      pod/test-frontend-integ-559e1a   Container image "frontend:v-fa43cc8321" already present on machine
10m         Normal   Created     pod/test-frontend-integ-559e1a   Created container main
10m         Normal   Started     pod/test-frontend-integ-559e1a   Started container main
10m         Normal   Killing     pod/test-frontend-integ-559e1a   Stopping container main
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Current Behavior
Currently Garden sometimes reports success, even though the test has been interrupted:

```
✔ frontend                  → Running integ tests → Success (took 40.8 sec)

Done! ✔️
```

This happens only on some Kubernetes clusters, e.g. `gke_garden-demo-324810_europe-west1-b_demo-3`.

On some other Kubernetes clusters Garden actually does the right thing and fails, for example on `gke_garden-ci_europe-west1-b_core-ci` Garden reports this error:

```
Unable to start command execution. Failed to initiate a runner pod with error:
Got error from Kubernetes API (readNamespacedPodStatus) - pods "test-frontend-integ-a197a5" not found
```

### Workaround

Not sure yet what is causing this. The Kubernetes API seems to be behaving differently.

### Suggested solution(s)

Unsure what is causing this.

### Your environment

* **OS:** MacOS
* **How I'm running Kubernetes:** GKE

* **Kubernetes version on `gke_garden-demo-324810_europe-west1-b_demo-3`**: `1.21.14-gke.5300`
* **Kubernetes version on `gke_garden-ci_europe-west1-b_core-ci`**: `1.22.15-gke.2500
--

`garden version` 0.12.48-edge-3e94f2b84

### PR DESCRIPTION
**Pull request by stefreak**
**What this PR does / why we need it**:
Detect that the pod has been killed, in order to
- improve the error message (relates to #3331)
- fix a bug where a test might have been reported as successful while it
  actually was killed (Fixes #3535)

This has been extracted from the PR #3537 (to keep it separate and merge
it more quickly)

**Which issue(s) this PR fixes**:

Fixes #3535

**Special notes for your reviewer**:
Screenshot 2023-01-24 at 15 53 40

### CODE REVIEW

File: core/src/plugins/kubernetes/run.ts [hunk 1]
```diff
@@ -1149,6 +1196,19 @@ export class PodRunner extends PodRunnerParams {
           }
 
           return errorDesc
+        case "not-found":
+          let notFoundError = dedent`
+            ${error.message}
+            There are several different possible causes for Pod disruptions.
+            You can read more about the topic in the Kubernetes documentation:
+            https://kubernetes.io/docs/concepts/workloads/pods/disruptions/`
```
Comment (stefreak) [inline core/src/plugins/kubernetes/run.ts:1204]:
```suggestion
            There are several different possible causes for Pod disruptions.

            You can read more about the topic in the Kubernetes documentation:
            https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
            `
```

File: core/src/plugins/kubernetes/run.ts [hunk 2]
```diff
@@ -822,6 +826,12 @@ export class PodRunner extends PodRunnerParams {
       // Wait until main container terminates
       const exitCode = await this.awaitRunningPod(params, startedAt)
 
+      const events = await getResourceEvents(this.api, this.pod)
```
Comment (eysi09) [inline core/src/plugins/kubernetes/run.ts:829]: Just a nitpick but I suppose we could refactor this into a helper function since it's used twice. 

Something like: `throwIfPodKilled`.

What do you think?

File: core/src/plugins/kubernetes/run.ts [hunk 3]
```diff
@@ -851,16 +862,45 @@ export class PodRunner extends PodRunnerParams {
...
+      let serverPod: KubernetesServerResource<V1Pod>
+      try {
+        serverPod = await this.api.core.readNamespacedPodStatus(podName, namespace)
+      } catch (e) {
+        if (e instanceof KubernetesError) {
+          // if the pod has been deleted during execution we might run into a 404 error.
+          // Convert it to Garden NotFoundError and fetch the logs for more details.
+          if (e.statusCode === 404) {
+            throw new NotFoundError(
+              "Pod disappeared while waiting for it to complete. The Pod might have been evicted or deleted.",
```
Comment (eysi09) [inline core/src/plugins/kubernetes/run.ts:887]: Is there a better word than "disappeared"? 

Maybe: `Encountered Pod "not found" error while waiting for it to complete. The Pod...`.

File: core/src/plugins/kubernetes/util.ts [hunk 4]
```diff
@@ -758,3 +758,23 @@ export function getK8sProvider(providers: ProviderMap): KubernetesProvider {
 export function usingInClusterRegistry(provider: KubernetesProvider) {
   return provider.config.deploymentRegistry?.hostname === inClusterRegistryHostname
 }
+
+export function renderPodEvents(events: CoreV1Event[]): string {
```
Comment (eysi09) [inline core/src/plugins/kubernetes/util.ts:762]: Nice! ✨

**Review by eysi09 — COMMENTED** [review]
Couple of small comments, otherwise looks good!

File: core/src/plugins/kubernetes/run.ts (hunk 3 above)
Comment (stefreak) [reply core/src/plugins/kubernetes/run.ts]: Went for `Could not find Pod while waiting for it to complete. The Pod might have been evicted or deleted.` because it is simpler language than `encountered`.

**Review by eysi09 — DISMISSED** [review]

**Comment by stefreak** [comment]
Sorry @eysi09 , had to dismiss your review as there was some Lint errors

**Review by eysi09 — APPROVED** [review]
