### PR TITLE
fix(k8s): fix rollout status check for Recreate

### LINKED ISSUE #2630: Incorrect status handling for deployment strategy "recreate"
### Current Behavior

When Garden deploys a Kubernetes module with the deployment strategy set to `recreate`, it will report the `Deployment` resource as ready immediately, even though in reality the initial Deployment is still being deleted and the new one not even created yet.

The `kubectl rollout status` command report the correct statuses.

### Expected behavior

Garden should wait for the deployment to be ready and in general behave like the `kubectl rollout status` command.

### Reproducible example

Deploy a Kubernetes module with the deployment strategy set to `recreate`. 

### Suggested solution(s)

In general our "wait for resources" handler is modelled after the `kubectl rollout status` source code, but I suppose there's some case there that we're not handling correctly.

### Additional context

Not sure if relevant but this particular resource also didn't have probes set.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

### PR DESCRIPTION
**Pull request by thsig**
**What this PR does / why we need it**:

@twelvemo and I paired on this.

Before this fix, the rollout status of deployments using the `Recreate` strategy would be reported as ready before the new pods were fully ready.

This was fixed by copying/following the latest logic from kubectl's rollout status checking logic, comparing the requested number of replicas from the deployment spec with the actual updated pod count.

See the [corresponding logic in kubectl](https://github.com/kubernetes/kubectl/blob/24d21a0ee42ecb5e5bed731f36b2d2c9c0244c35/pkg/polymorphichelpers/rollout_status.go).

**Which issue(s) this PR fixes**:

Fixes #2630 and #2717.

### CODE REVIEW

File: core/src/plugins/kubernetes/status/workload.ts [hunk 1]
```diff
@@ -224,8 +225,9 @@ async function getRolloutStatus(workload: Workload) {
     }
   } else {
     const status = <V1DeploymentStatus>workload.status
+    const deploymentSpec = <V1DeploymentSpec>workload.spec
 
-    const desired = status.replicas || 0
+    const desired = deploymentSpec.replicas || 0
```
Comment (edvald) [inline core/src/plugins/kubernetes/status/workload.ts:230]: I suspect the default value here should be 1

Comment (thsig) [reply core/src/plugins/kubernetes/status/workload.ts:230]: Hmm, what it the deployment is being scaled down to 0?

Comment (thsig) [reply core/src/plugins/kubernetes/status/workload.ts]: Should be good to go now.

**Review by edvald — APPROVED** [review]
